/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * BulkStopMemoryGeneratorsRequest.h
 *
 * Parameters for the bulk stop operation
 */

#ifndef BulkStopMemoryGeneratorsRequest_H_
#define BulkStopMemoryGeneratorsRequest_H_


#include "ModelBase.h"

#include <string>
#include <vector>

namespace swagger {
namespace v1 {
namespace model {

/// <summary>
/// Parameters for the bulk stop operation
/// </summary>
class  BulkStopMemoryGeneratorsRequest
    : public ModelBase
{
public:
    BulkStopMemoryGeneratorsRequest();
    virtual ~BulkStopMemoryGeneratorsRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// BulkStopMemoryGeneratorsRequest members

    /// <summary>
    /// List of memory generator identifiers
    /// </summary>
    std::vector<std::string>& getIds();
    
protected:
    std::vector<std::string> m_Ids;

};

}
}
}

#endif /* BulkStopMemoryGeneratorsRequest_H_ */
