/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * BulkCreateNetworkServersRequest.h
 *
 * Parameters for the bulk create operation
 */

#ifndef BulkCreateNetworkServersRequest_H_
#define BulkCreateNetworkServersRequest_H_


#include "ModelBase.h"

#include "NetworkServer.h"
#include <vector>

namespace swagger {
namespace v1 {
namespace model {

/// <summary>
/// Parameters for the bulk create operation
/// </summary>
class  BulkCreateNetworkServersRequest
    : public ModelBase
{
public:
    BulkCreateNetworkServersRequest();
    virtual ~BulkCreateNetworkServersRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// BulkCreateNetworkServersRequest members

    /// <summary>
    /// List of network server
    /// </summary>
    std::vector<std::shared_ptr<NetworkServer>>& getItems();
    
protected:
    std::vector<std::shared_ptr<NetworkServer>> m_Items;

};

}
}
}

#endif /* BulkCreateNetworkServersRequest_H_ */
