/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * BulkStartMemoryGeneratorsRequest.h
 *
 * Parameters for the bulk start operation
 */

#ifndef BulkStartMemoryGeneratorsRequest_H_
#define BulkStartMemoryGeneratorsRequest_H_


#include "ModelBase.h"

#include <string>
#include <vector>

namespace swagger {
namespace v1 {
namespace model {

/// <summary>
/// Parameters for the bulk start operation
/// </summary>
class  BulkStartMemoryGeneratorsRequest
    : public ModelBase
{
public:
    BulkStartMemoryGeneratorsRequest();
    virtual ~BulkStartMemoryGeneratorsRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// BulkStartMemoryGeneratorsRequest members

    /// <summary>
    /// List of memory generator identifiers
    /// </summary>
    std::vector<std::string>& getIds();
    
protected:
    std::vector<std::string> m_Ids;

};

}
}
}

#endif /* BulkStartMemoryGeneratorsRequest_H_ */
