/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * BulkCreateBlockGeneratorsResponse.h
 *
 * 
 */

#ifndef BulkCreateBlockGeneratorsResponse_H_
#define BulkCreateBlockGeneratorsResponse_H_


#include "ModelBase.h"

#include "BlockGenerator.h"
#include <vector>

namespace swagger {
namespace v1 {
namespace model {

/// <summary>
/// 
/// </summary>
class  BulkCreateBlockGeneratorsResponse
    : public ModelBase
{
public:
    BulkCreateBlockGeneratorsResponse();
    virtual ~BulkCreateBlockGeneratorsResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// BulkCreateBlockGeneratorsResponse members

    /// <summary>
    /// List of created block generators
    /// </summary>
    std::vector<std::shared_ptr<BlockGenerator>>& getItems();
    
protected:
    std::vector<std::shared_ptr<BlockGenerator>> m_Items;

};

}
}
}

#endif /* BulkCreateBlockGeneratorsResponse_H_ */
