/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "CpuGeneratorCoreConfig_targets.h"

namespace swagger {
namespace v1 {
namespace model {

CpuGeneratorCoreConfig_targets::CpuGeneratorCoreConfig_targets()
{
    m_Weight = 0;
    
}

CpuGeneratorCoreConfig_targets::~CpuGeneratorCoreConfig_targets()
{
}

void CpuGeneratorCoreConfig_targets::validate()
{
    // TODO: implement validation
}

nlohmann::json CpuGeneratorCoreConfig_targets::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["load"] = ModelBase::toJson(m_Load);
    val["weight"] = m_Weight;
    

    return val;
}

void CpuGeneratorCoreConfig_targets::fromJson(nlohmann::json& val)
{
    setWeight(val.at("weight"));
    
}


std::shared_ptr<CpuGeneratorCoreLoad> CpuGeneratorCoreConfig_targets::getLoad() const
{
    return m_Load;
}
void CpuGeneratorCoreConfig_targets::setLoad(std::shared_ptr<CpuGeneratorCoreLoad> value)
{
    m_Load = value;
    
}
int32_t CpuGeneratorCoreConfig_targets::getWeight() const
{
    return m_Weight;
}
void CpuGeneratorCoreConfig_targets::setWeight(int32_t value)
{
    m_Weight = value;
    
}

}
}
}

