/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "CpuGeneratorSystemConfig.h"

namespace swagger {
namespace v1 {
namespace model {

CpuGeneratorSystemConfig::CpuGeneratorSystemConfig()
{
    m_Utilization = 0.0;
    
}

CpuGeneratorSystemConfig::~CpuGeneratorSystemConfig()
{
}

void CpuGeneratorSystemConfig::validate()
{
    // TODO: implement validation
}

nlohmann::json CpuGeneratorSystemConfig::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["utilization"] = m_Utilization;
    

    return val;
}

void CpuGeneratorSystemConfig::fromJson(nlohmann::json& val)
{
    setUtilization(val.at("utilization"));
    
}


double CpuGeneratorSystemConfig::getUtilization() const
{
    return m_Utilization;
}
void CpuGeneratorSystemConfig::setUtilization(double value)
{
    m_Utilization = value;
    
}

}
}
}

