/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "CpuGeneratorTargetStats.h"

namespace swagger {
namespace v1 {
namespace model {

CpuGeneratorTargetStats::CpuGeneratorTargetStats()
{
    m_Cycles = 0L;
    
}

CpuGeneratorTargetStats::~CpuGeneratorTargetStats()
{
}

void CpuGeneratorTargetStats::validate()
{
    // TODO: implement validation
}

nlohmann::json CpuGeneratorTargetStats::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["cycles"] = m_Cycles;
    

    return val;
}

void CpuGeneratorTargetStats::fromJson(nlohmann::json& val)
{
    setCycles(val.at("cycles"));
    
}


int64_t CpuGeneratorTargetStats::getCycles() const
{
    return m_Cycles;
}
void CpuGeneratorTargetStats::setCycles(int64_t value)
{
    m_Cycles = value;
    
}

}
}
}

