/**
* Inception Core API
* REST API interface to the Inception Core
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * InterfaceProtocolConfig_ipv4_dhcp.h
 *
 * DHCP configuration parameters
 */

#ifndef InterfaceProtocolConfig_ipv4_dhcp_H_
#define InterfaceProtocolConfig_ipv4_dhcp_H_


#include "ModelBase.h"

#include <string>

namespace swagger {
namespace v1 {
namespace model {

/// <summary>
/// DHCP configuration parameters
/// </summary>
class  InterfaceProtocolConfig_ipv4_dhcp
    : public ModelBase
{
public:
    InterfaceProtocolConfig_ipv4_dhcp();
    virtual ~InterfaceProtocolConfig_ipv4_dhcp();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// InterfaceProtocolConfig_ipv4_dhcp members

    /// <summary>
    /// Hostname to be requested
    /// </summary>
    std::string getHostname() const;
    void setHostname(std::string value);
    bool hostnameIsSet() const;
    void unsetHostname();
    /// <summary>
    /// Client identifier
    /// </summary>
    std::string getClient() const;
    void setClient(std::string value);
    bool clientIsSet() const;
    void unsetClient();

protected:
    std::string m_Hostname;
    bool m_HostnameIsSet;
    std::string m_Client;
    bool m_ClientIsSet;
};

}
}
}

#endif /* InterfaceProtocolConfig_ipv4_dhcp_H_ */
