/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * MacAddress.h
 *
 * Ethernet MAC address
 */

#ifndef MacAddress_H_
#define MacAddress_H_


#include "ModelBase.h"


namespace swagger {
namespace v1 {
namespace model {

/// <summary>
/// Ethernet MAC address
/// </summary>
class  MacAddress
    : public ModelBase
{
public:
    MacAddress();
    virtual ~MacAddress();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// MacAddress members


protected:
};

}
}
}

#endif /* MacAddress_H_ */
