/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "MemoryInfoResult.h"

namespace swagger {
namespace v1 {
namespace model {

MemoryInfoResult::MemoryInfoResult()
{
    m_Total_memory = 0L;
    m_Total_memoryIsSet = false;
    m_Free_memory = 0L;
    m_Free_memoryIsSet = false;
    
}

MemoryInfoResult::~MemoryInfoResult()
{
}

void MemoryInfoResult::validate()
{
    // TODO: implement validation
}

nlohmann::json MemoryInfoResult::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    if(m_Total_memoryIsSet)
    {
        val["total_memory"] = m_Total_memory;
    }
    if(m_Free_memoryIsSet)
    {
        val["free_memory"] = m_Free_memory;
    }
    

    return val;
}

void MemoryInfoResult::fromJson(nlohmann::json& val)
{
    if(val.find("total_memory") != val.end())
    {
        setTotalMemory(val.at("total_memory"));
    }
    if(val.find("free_memory") != val.end())
    {
        setFreeMemory(val.at("free_memory"));
    }
    
}


int64_t MemoryInfoResult::getTotalMemory() const
{
    return m_Total_memory;
}
void MemoryInfoResult::setTotalMemory(int64_t value)
{
    m_Total_memory = value;
    m_Total_memoryIsSet = true;
}
bool MemoryInfoResult::totalMemoryIsSet() const
{
    return m_Total_memoryIsSet;
}
void MemoryInfoResult::unsetTotal_memory()
{
    m_Total_memoryIsSet = false;
}
int64_t MemoryInfoResult::getFreeMemory() const
{
    return m_Free_memory;
}
void MemoryInfoResult::setFreeMemory(int64_t value)
{
    m_Free_memory = value;
    m_Free_memoryIsSet = true;
}
bool MemoryInfoResult::freeMemoryIsSet() const
{
    return m_Free_memoryIsSet;
}
void MemoryInfoResult::unsetFree_memory()
{
    m_Free_memoryIsSet = false;
}

}
}
}

