/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * NetworkGenerator.h
 *
 * Network generator
 */

#ifndef NetworkGenerator_H_
#define NetworkGenerator_H_


#include "ModelBase.h"

#include <string>
#include "NetworkGeneratorConfig.h"

namespace swagger {
namespace v1 {
namespace model {

/// <summary>
/// Network generator
/// </summary>
class  NetworkGenerator
    : public ModelBase
{
public:
    NetworkGenerator();
    virtual ~NetworkGenerator();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// NetworkGenerator members

    /// <summary>
    /// Unique network generator identifier
    /// </summary>
    std::string getId() const;
    void setId(std::string value);
        /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<NetworkGeneratorConfig> getConfig() const;
    void setConfig(std::shared_ptr<NetworkGeneratorConfig> value);
        /// <summary>
    /// Indicates whether this generator is currently running.
    /// </summary>
    bool isRunning() const;
    void setRunning(bool value);
    
protected:
    std::string m_Id;

    std::shared_ptr<NetworkGeneratorConfig> m_Config;

    bool m_Running;

};

}
}
}

#endif /* NetworkGenerator_H_ */
