/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "NetworkGeneratorConfig_target.h"

namespace swagger {
namespace v1 {
namespace model {

NetworkGeneratorConfig_target::NetworkGeneratorConfig_target()
{
    m_Host = "";
    m_Port = 0L;
    m_Protocol = "";
    m_Driver = "";
    
}

NetworkGeneratorConfig_target::~NetworkGeneratorConfig_target()
{
}

void NetworkGeneratorConfig_target::validate()
{
    // TODO: implement validation
}

nlohmann::json NetworkGeneratorConfig_target::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["host"] = ModelBase::toJson(m_Host);
    val["port"] = m_Port;
    val["protocol"] = ModelBase::toJson(m_Protocol);
    val["driver"] = ModelBase::toJson(m_Driver);
    

    return val;
}

void NetworkGeneratorConfig_target::fromJson(nlohmann::json& val)
{
    setHost(val.at("host"));
    setPort(val.at("port"));
    setProtocol(val.at("protocol"));
    setDriver(val.at("driver"));
    
}


std::string NetworkGeneratorConfig_target::getHost() const
{
    return m_Host;
}
void NetworkGeneratorConfig_target::setHost(std::string value)
{
    m_Host = value;
    
}
int64_t NetworkGeneratorConfig_target::getPort() const
{
    return m_Port;
}
void NetworkGeneratorConfig_target::setPort(int64_t value)
{
    m_Port = value;
    
}
std::string NetworkGeneratorConfig_target::getProtocol() const
{
    return m_Protocol;
}
void NetworkGeneratorConfig_target::setProtocol(std::string value)
{
    m_Protocol = value;
    
}
std::string NetworkGeneratorConfig_target::getDriver() const
{
    return m_Driver;
}
void NetworkGeneratorConfig_target::setDriver(std::string value)
{
    m_Driver = value;
    
}

}
}
}

