/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * PacketProtocolMpls.h
 *
 * Describes a MPLS header
 */

#ifndef PacketProtocolMpls_H_
#define PacketProtocolMpls_H_


#include "ModelBase.h"


namespace swagger {
namespace v1 {
namespace model {

/// <summary>
/// Describes a MPLS header
/// </summary>
class  PacketProtocolMpls
    : public ModelBase
{
public:
    PacketProtocolMpls();
    virtual ~PacketProtocolMpls();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// PacketProtocolMpls members

    /// <summary>
    /// MPLS bottom of stack
    /// </summary>
    bool isBottomOfStack() const;
    void setBottomOfStack(bool value);
    bool bottomOfStackIsSet() const;
    void unsetBottom_of_stack();
    /// <summary>
    /// MPLS label
    /// </summary>
    int32_t getLabel() const;
    void setLabel(int32_t value);
    bool labelIsSet() const;
    void unsetLabel();
    /// <summary>
    /// MPLS traffic class
    /// </summary>
    int32_t getTrafficClass() const;
    void setTrafficClass(int32_t value);
    bool trafficClassIsSet() const;
    void unsetTraffic_class();
    /// <summary>
    /// MPLS ttl
    /// </summary>
    int32_t getTtl() const;
    void setTtl(int32_t value);
    bool ttlIsSet() const;
    void unsetTtl();

protected:
    bool m_Bottom_of_stack;
    bool m_Bottom_of_stackIsSet;
    int32_t m_Label;
    bool m_LabelIsSet;
    int32_t m_Traffic_class;
    bool m_Traffic_classIsSet;
    int32_t m_Ttl;
    bool m_TtlIsSet;
};

}
}
}

#endif /* PacketProtocolMpls_H_ */
