/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * PacketAnalyzerFlowCounters_jitter_ipdv.h
 *
 * Jitter (RFC 3393) result counters
 */

#ifndef PacketAnalyzerFlowCounters_jitter_ipdv_H_
#define PacketAnalyzerFlowCounters_jitter_ipdv_H_


#include "ModelBase.h"

#include "PacketAnalyzerFlowSummaryCounters.h"
#include <string>

namespace swagger {
namespace v1 {
namespace model {

/// <summary>
/// Jitter (RFC 3393) result counters
/// </summary>
class  PacketAnalyzerFlowCounters_jitter_ipdv
    : public ModelBase
{
public:
    PacketAnalyzerFlowCounters_jitter_ipdv();
    virtual ~PacketAnalyzerFlowCounters_jitter_ipdv();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// PacketAnalyzerFlowCounters_jitter_ipdv members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<PacketAnalyzerFlowSummaryCounters> getSummary() const;
    void setSummary(std::shared_ptr<PacketAnalyzerFlowSummaryCounters> value);
        /// <summary>
    /// Jitter time measurement units
    /// </summary>
    std::string getUnits() const;
    void setUnits(std::string value);
    
protected:
    std::shared_ptr<PacketAnalyzerFlowSummaryCounters> m_Summary;

    std::string m_Units;

};

}
}
}

#endif /* PacketAnalyzerFlowCounters_jitter_ipdv_H_ */
