/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "TcpIpPort.h"

namespace swagger {
namespace v1 {
namespace model {

TcpIpPort::TcpIpPort()
{
    
}

TcpIpPort::~TcpIpPort()
{
}

void TcpIpPort::validate()
{
    // TODO: implement validation
}

nlohmann::json TcpIpPort::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    

    return val;
}

void TcpIpPort::fromJson(nlohmann::json& val)
{
    
}



}
}
}

