/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "TDigestCentroid.h"

namespace swagger {
namespace v1 {
namespace model {

TDigestCentroid::TDigestCentroid()
{
    m_Mean = 0.0;
    m_Weight = 0;
    
}

TDigestCentroid::~TDigestCentroid()
{
}

void TDigestCentroid::validate()
{
    // TODO: implement validation
}

nlohmann::json TDigestCentroid::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["mean"] = m_Mean;
    val["weight"] = m_Weight;
    

    return val;
}

void TDigestCentroid::fromJson(nlohmann::json& val)
{
    setMean(val.at("mean"));
    setWeight(val.at("weight"));
    
}


double TDigestCentroid::getMean() const
{
    return m_Mean;
}
void TDigestCentroid::setMean(double value)
{
    m_Mean = value;
    
}
int32_t TDigestCentroid::getWeight() const
{
    return m_Weight;
}
void TDigestCentroid::setWeight(int32_t value)
{
    m_Weight = value;
    
}

}
}
}

