/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * ThresholdResult.h
 *
 * Threshold result
 */

#ifndef ThresholdResult_H_
#define ThresholdResult_H_


#include "ModelBase.h"

#include <string>

namespace swagger {
namespace v1 {
namespace model {

/// <summary>
/// Threshold result
/// </summary>
class  ThresholdResult
    : public ModelBase
{
public:
    ThresholdResult();
    virtual ~ThresholdResult();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// ThresholdResult members

    /// <summary>
    /// Unique identifier of result of generator
    /// </summary>
    std::string getResultId() const;
    void setResultId(std::string value);
        /// <summary>
    /// Threshold configuration unique identifier
    /// </summary>
    std::string getThresholdId() const;
    void setThresholdId(std::string value);
        /// <summary>
    /// The ISO8601-formatted date of the last result update
    /// </summary>
    std::string getTimestamp() const;
    void setTimestamp(std::string value);
        /// <summary>
    /// Counter of true conditions
    /// </summary>
    int32_t getConditionTrue() const;
    void setConditionTrue(int32_t value);
        /// <summary>
    /// Counter of false conditions
    /// </summary>
    int32_t getConditionFalse() const;
    void setConditionFalse(int32_t value);
    
protected:
    std::string m_Result_id;

    std::string m_Threshold_id;

    std::string m_Timestamp;

    int32_t m_Condition_true;

    int32_t m_Condition_false;

};

}
}
}

#endif /* ThresholdResult_H_ */
