/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "TimeCounter.h"

namespace swagger {
namespace v1 {
namespace model {

TimeCounter::TimeCounter()
{
    m_Id = "";
    m_Name = "";
    m_Frequency = 0L;
    m_Priority = 0;
    
}

TimeCounter::~TimeCounter()
{
}

void TimeCounter::validate()
{
    // TODO: implement validation
}

nlohmann::json TimeCounter::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["id"] = ModelBase::toJson(m_Id);
    val["name"] = ModelBase::toJson(m_Name);
    val["frequency"] = m_Frequency;
    val["priority"] = m_Priority;
    

    return val;
}

void TimeCounter::fromJson(nlohmann::json& val)
{
    setId(val.at("id"));
    setName(val.at("name"));
    setFrequency(val.at("frequency"));
    setPriority(val.at("priority"));
    
}


std::string TimeCounter::getId() const
{
    return m_Id;
}
void TimeCounter::setId(std::string value)
{
    m_Id = value;
    
}
std::string TimeCounter::getName() const
{
    return m_Name;
}
void TimeCounter::setName(std::string value)
{
    m_Name = value;
    
}
int64_t TimeCounter::getFrequency() const
{
    return m_Frequency;
}
void TimeCounter::setFrequency(int64_t value)
{
    m_Frequency = value;
    
}
int32_t TimeCounter::getPriority() const
{
    return m_Priority;
}
void TimeCounter::setPriority(int32_t value)
{
    m_Priority = value;
    
}

}
}
}

