/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "TogglePacketGeneratorsRequest.h"

namespace swagger {
namespace v1 {
namespace model {

TogglePacketGeneratorsRequest::TogglePacketGeneratorsRequest()
{
    m_Replace = "";
    m_With = "";
    
}

TogglePacketGeneratorsRequest::~TogglePacketGeneratorsRequest()
{
}

void TogglePacketGeneratorsRequest::validate()
{
    // TODO: implement validation
}

nlohmann::json TogglePacketGeneratorsRequest::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["replace"] = ModelBase::toJson(m_Replace);
    val["with"] = ModelBase::toJson(m_With);
    

    return val;
}

void TogglePacketGeneratorsRequest::fromJson(nlohmann::json& val)
{
    setReplace(val.at("replace"));
    setWith(val.at("with"));
    
}


std::string TogglePacketGeneratorsRequest::getReplace() const
{
    return m_Replace;
}
void TogglePacketGeneratorsRequest::setReplace(std::string value)
{
    m_Replace = value;
    
}
std::string TogglePacketGeneratorsRequest::getWith() const
{
    return m_With;
}
void TogglePacketGeneratorsRequest::setWith(std::string value)
{
    m_With = value;
    
}

}
}
}

