/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "TrafficLength_fixed.h"

namespace swagger {
namespace v1 {
namespace model {

TrafficLength_fixed::TrafficLength_fixed()
{
    m_Length = 0;
    
}

TrafficLength_fixed::~TrafficLength_fixed()
{
}

void TrafficLength_fixed::validate()
{
    // TODO: implement validation
}

nlohmann::json TrafficLength_fixed::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["length"] = m_Length;
    

    return val;
}

void TrafficLength_fixed::fromJson(nlohmann::json& val)
{
    setLength(val.at("length"));
    
}


int32_t TrafficLength_fixed::getLength() const
{
    return m_Length;
}
void TrafficLength_fixed::setLength(int32_t value)
{
    m_Length = value;
    
}

}
}
}

