/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * TrafficLength_list.h
 *
 * Specifies a list of packet lengths
 */

#ifndef TrafficLength_list_H_
#define TrafficLength_list_H_


#include "ModelBase.h"

#include <vector>

namespace swagger {
namespace v1 {
namespace model {

/// <summary>
/// Specifies a list of packet lengths
/// </summary>
class  TrafficLength_list
    : public ModelBase
{
public:
    TrafficLength_list();
    virtual ~TrafficLength_list();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// TrafficLength_list members

    /// <summary>
    /// List of packet lengths
    /// </summary>
    std::vector<int32_t>& getLengths();
    
protected:
    std::vector<int32_t> m_Lengths;

};

}
}
}

#endif /* TrafficLength_list_H_ */
