/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "TrafficProtocolIpv4Modifier.h"

namespace swagger {
namespace v1 {
namespace model {

TrafficProtocolIpv4Modifier::TrafficProtocolIpv4Modifier()
{
    m_ListIsSet = false;
    m_SequenceIsSet = false;
    
}

TrafficProtocolIpv4Modifier::~TrafficProtocolIpv4Modifier()
{
}

void TrafficProtocolIpv4Modifier::validate()
{
    // TODO: implement validation
}

nlohmann::json TrafficProtocolIpv4Modifier::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    {
        nlohmann::json jsonArray;
        for( auto& item : m_List )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            val["list"] = jsonArray;
        }
    }
    if(m_SequenceIsSet)
    {
        val["sequence"] = ModelBase::toJson(m_Sequence);
    }
    

    return val;
}

void TrafficProtocolIpv4Modifier::fromJson(nlohmann::json& val)
{
    {
        m_List.clear();
        nlohmann::json jsonArray;
        if(val.find("list") != val.end())
        {
        for( auto& item : val["list"] )
        {
            m_List.push_back(item);
            
        }
        }
    }
    if(val.find("sequence") != val.end())
    {
        if(!val["sequence"].is_null())
        {
            std::shared_ptr<TrafficProtocolIpv4Modifier_sequence> newItem(new TrafficProtocolIpv4Modifier_sequence());
            newItem->fromJson(val["sequence"]);
            setSequence( newItem );
        }
        
    }
    
}


std::vector<std::string>& TrafficProtocolIpv4Modifier::getList()
{
    return m_List;
}
bool TrafficProtocolIpv4Modifier::listIsSet() const
{
    return m_ListIsSet;
}
void TrafficProtocolIpv4Modifier::unsetList()
{
    m_ListIsSet = false;
}
std::shared_ptr<TrafficProtocolIpv4Modifier_sequence> TrafficProtocolIpv4Modifier::getSequence() const
{
    return m_Sequence;
}
void TrafficProtocolIpv4Modifier::setSequence(std::shared_ptr<TrafficProtocolIpv4Modifier_sequence> value)
{
    m_Sequence = value;
    m_SequenceIsSet = true;
}
bool TrafficProtocolIpv4Modifier::sequenceIsSet() const
{
    return m_SequenceIsSet;
}
void TrafficProtocolIpv4Modifier::unsetSequence()
{
    m_SequenceIsSet = false;
}

}
}
}

