/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "TrafficLoad.h"

namespace swagger {
namespace v1 {
namespace model {

TrafficLoad::TrafficLoad()
{
    m_Burst = 0;
    m_BurstIsSet = false;
    m_Units = "";
    
}

TrafficLoad::~TrafficLoad()
{
}

void TrafficLoad::validate()
{
    // TODO: implement validation
}

nlohmann::json TrafficLoad::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    if(m_BurstIsSet)
    {
        val["burst"] = m_Burst;
    }
    val["rate"] = ModelBase::toJson(m_Rate);
    val["units"] = ModelBase::toJson(m_Units);
    

    return val;
}

void TrafficLoad::fromJson(nlohmann::json& val)
{
    if(val.find("burst") != val.end())
    {
        setBurst(val.at("burst"));
    }
    setUnits(val.at("units"));
    
}


int32_t TrafficLoad::getBurst() const
{
    return m_Burst;
}
void TrafficLoad::setBurst(int32_t value)
{
    m_Burst = value;
    m_BurstIsSet = true;
}
bool TrafficLoad::burstIsSet() const
{
    return m_BurstIsSet;
}
void TrafficLoad::unsetBurst()
{
    m_BurstIsSet = false;
}
std::shared_ptr<TrafficLoad_rate> TrafficLoad::getRate() const
{
    return m_Rate;
}
void TrafficLoad::setRate(std::shared_ptr<TrafficLoad_rate> value)
{
    m_Rate = value;
    
}
std::string TrafficLoad::getUnits() const
{
    return m_Units;
}
void TrafficLoad::setUnits(std::string value)
{
    m_Units = value;
    
}

}
}
}

