/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * TrafficLength_fixed.h
 *
 * Specifies a fixed packet lengths
 */

#ifndef TrafficLength_fixed_H_
#define TrafficLength_fixed_H_


#include "ModelBase.h"


namespace swagger {
namespace v1 {
namespace model {

/// <summary>
/// Specifies a fixed packet lengths
/// </summary>
class  TrafficLength_fixed
    : public ModelBase
{
public:
    TrafficLength_fixed();
    virtual ~TrafficLength_fixed();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// TrafficLength_fixed members

    /// <summary>
    /// Fixed packet length
    /// </summary>
    int32_t getLength() const;
    void setLength(int32_t value);
    
protected:
    int32_t m_Length;

};

}
}
}

#endif /* TrafficLength_fixed_H_ */
