/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "TvlpConfiguration.h"

namespace swagger {
namespace v1 {
namespace model {

TvlpConfiguration::TvlpConfiguration()
{
    m_Id = "";
    m_State = "";
    m_Load_scale = 0.0;
    m_Time_scale = 0.0;
    m_Error = "";
    m_ErrorIsSet = false;
    
}

TvlpConfiguration::~TvlpConfiguration()
{
}

void TvlpConfiguration::validate()
{
    // TODO: implement validation
}

nlohmann::json TvlpConfiguration::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["id"] = ModelBase::toJson(m_Id);
    val["state"] = ModelBase::toJson(m_State);
    val["load_scale"] = m_Load_scale;
    val["time_scale"] = m_Time_scale;
    val["time"] = ModelBase::toJson(m_Time);
    val["profile"] = ModelBase::toJson(m_Profile);
    if(m_ErrorIsSet)
    {
        val["error"] = ModelBase::toJson(m_Error);
    }
    

    return val;
}

void TvlpConfiguration::fromJson(nlohmann::json& val)
{
    setId(val.at("id"));
    setState(val.at("state"));
    setLoadScale(val.at("load_scale"));
    setTimeScale(val.at("time_scale"));
    if(val.find("error") != val.end())
    {
        setError(val.at("error"));
        
    }
    
}


std::string TvlpConfiguration::getId() const
{
    return m_Id;
}
void TvlpConfiguration::setId(std::string value)
{
    m_Id = value;
    
}
std::string TvlpConfiguration::getState() const
{
    return m_State;
}
void TvlpConfiguration::setState(std::string value)
{
    m_State = value;
    
}
double TvlpConfiguration::getLoadScale() const
{
    return m_Load_scale;
}
void TvlpConfiguration::setLoadScale(double value)
{
    m_Load_scale = value;
    
}
double TvlpConfiguration::getTimeScale() const
{
    return m_Time_scale;
}
void TvlpConfiguration::setTimeScale(double value)
{
    m_Time_scale = value;
    
}
std::shared_ptr<TvlpConfiguration_time> TvlpConfiguration::getTime() const
{
    return m_Time;
}
void TvlpConfiguration::setTime(std::shared_ptr<TvlpConfiguration_time> value)
{
    m_Time = value;
    
}
std::shared_ptr<TvlpProfile> TvlpConfiguration::getProfile() const
{
    return m_Profile;
}
void TvlpConfiguration::setProfile(std::shared_ptr<TvlpProfile> value)
{
    m_Profile = value;
    
}
std::string TvlpConfiguration::getError() const
{
    return m_Error;
}
void TvlpConfiguration::setError(std::string value)
{
    m_Error = value;
    m_ErrorIsSet = true;
}
bool TvlpConfiguration::errorIsSet() const
{
    return m_ErrorIsSet;
}
void TvlpConfiguration::unsetError()
{
    m_ErrorIsSet = false;
}

}
}
}

