/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "TvlpProfile_cpu.h"

namespace swagger {
namespace v1 {
namespace model {

TvlpProfile_cpu::TvlpProfile_cpu()
{
    m_SeriesIsSet = false;
    
}

TvlpProfile_cpu::~TvlpProfile_cpu()
{
}

void TvlpProfile_cpu::validate()
{
    // TODO: implement validation
}

nlohmann::json TvlpProfile_cpu::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    {
        nlohmann::json jsonArray;
        for( auto& item : m_Series )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            val["series"] = jsonArray;
        }
    }
    

    return val;
}

void TvlpProfile_cpu::fromJson(nlohmann::json& val)
{
    {
        m_Series.clear();
        nlohmann::json jsonArray;
        if(val.find("series") != val.end())
        {
        for( auto& item : val["series"] )
        {
            
            if(item.is_null())
            {
                m_Series.push_back( std::shared_ptr<TvlpProfile_cpu_series>(nullptr) );
            }
            else
            {
                std::shared_ptr<TvlpProfile_cpu_series> newItem(new TvlpProfile_cpu_series());
                newItem->fromJson(item);
                m_Series.push_back( newItem );
            }
            
        }
        }
    }
    
}


std::vector<std::shared_ptr<TvlpProfile_cpu_series>>& TvlpProfile_cpu::getSeries()
{
    return m_Series;
}
bool TvlpProfile_cpu::seriesIsSet() const
{
    return m_SeriesIsSet;
}
void TvlpProfile_cpu::unsetSeries()
{
    m_SeriesIsSet = false;
}

}
}
}

