/**
* OpenPerf API
* REST API interface for OpenPerf
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "TvlpProfile_block_series.h"

namespace swagger {
namespace v1 {
namespace model {

TvlpProfile_block_series::TvlpProfile_block_series()
{
    m_Resource_id = "";
    m_Length = 0L;
    
}

TvlpProfile_block_series::~TvlpProfile_block_series()
{
}

void TvlpProfile_block_series::validate()
{
    // TODO: implement validation
}

nlohmann::json TvlpProfile_block_series::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["resource_id"] = ModelBase::toJson(m_Resource_id);
    val["length"] = m_Length;
    val["config"] = ModelBase::toJson(m_Config);
    

    return val;
}

void TvlpProfile_block_series::fromJson(nlohmann::json& val)
{
    setResourceId(val.at("resource_id"));
    setLength(val.at("length"));
    
}


std::string TvlpProfile_block_series::getResourceId() const
{
    return m_Resource_id;
}
void TvlpProfile_block_series::setResourceId(std::string value)
{
    m_Resource_id = value;
    
}
int64_t TvlpProfile_block_series::getLength() const
{
    return m_Length;
}
void TvlpProfile_block_series::setLength(int64_t value)
{
    m_Length = value;
    
}
std::shared_ptr<BlockGeneratorConfig> TvlpProfile_block_series::getConfig() const
{
    return m_Config;
}
void TvlpProfile_block_series::setConfig(std::shared_ptr<BlockGeneratorConfig> value)
{
    m_Config = value;
    
}

}
}
}

