#ifndef _OP_PACKET_PROTOCOL_TRANSMOGRIFY_PROTOCOLS_HPP_
#define _OP_PACKET_PROTOCOL_TRANSMOGRIFY_PROTOCOLS_HPP_

/**
 * This file is automatically generated. Do not edit!
 **/

#include "packet/protocol/transmogrify/ethernet.hpp"
#include "packet/protocol/transmogrify/ipv4.hpp"
#include "packet/protocol/transmogrify/ipv6.hpp"
#include "packet/protocol/transmogrify/mpls.hpp"
#include "packet/protocol/transmogrify/tcp.hpp"
#include "packet/protocol/transmogrify/udp.hpp"
#include "packet/protocol/transmogrify/vlan.hpp"

#endif /* _OP_PACKET_PROTOCOL_TRANSMOGRIFY_PROTOCOLS_HPP_ */
