;;; Update include path for clang
;;; Oh, DPDK...  What is wrong with you?
((nil . ((eval . (let ((root (projectile-project-root)))
                   (setq-local flycheck-clang-include-path
                               (list (concat root "deps/catch/include")
                                     (concat root "deps/dpdk/lib/librte_acl")
                                     (concat root "deps/dpdk/lib/librte_bbdev")
                                     (concat root "deps/dpdk/lib/librte_bitratestats")
                                     (concat root "deps/dpdk/lib/librte_bpf")
                                     (concat root "deps/dpdk/lib/librte_cfgfile")
                                     (concat root "deps/dpdk/lib/librte_cmdline")
                                     (concat root "deps/dpdk/lib/librte_compat")
                                     (concat root "deps/dpdk/lib/librte_compressdev")
                                     (concat root "deps/dpdk/lib/librte_cryptodev")
                                     (concat root "deps/dpdk/lib/librte_distributor")
                                     (concat root "deps/dpdk/lib/librte_eal/common/include")
                                     (concat root "deps/dpdk/lib/librte_efd")
                                     (concat root "deps/dpdk/lib/librte_ethdev")
                                     (concat root "deps/dpdk/lib/librte_eventdev")
                                     (concat root "deps/dpdk/lib/librte_flow_classify")
                                     (concat root "deps/dpdk/lib/librte_gro")
                                     (concat root "deps/dpdk/lib/librte_gso")
                                     (concat root "deps/dpdk/lib/librte_ip_frag")
                                     (concat root "deps/dpdk/lib/librte_jobstats")
                                     (concat root "deps/dpdk/lib/librte_kni")
                                     (concat root "deps/dpdk/lib/librte_kvargs")
                                     (concat root "deps/dpdk/lib/librte_latencystats")
                                     (concat root "deps/dpdk/lib/librte_lpm")
                                     (concat root "deps/dpdk/lib/librte_mbuf")
                                     (concat root "deps/dpdk/lib/librte_member")
                                     (concat root "deps/dpdk/lib/librte_mempool")
                                     (concat root "deps/dpdk/lib/librte_meter")
                                     (concat root "deps/dpdk/lib/librte_metrics")
                                     (concat root "deps/dpdk/lib/librte_net")
                                     (concat root "deps/dpdk/lib/librte_pci")
                                     (concat root "deps/dpdk/lib/librte_pdump")
                                     (concat root "deps/dpdk/lib/librte_pipeline")
                                     (concat root "deps/dpdk/lib/librte_port")
                                     (concat root "deps/dpdk/lib/librte_power")
                                     (concat root "deps/dpdk/lib/librte_rawdev")
                                     (concat root "deps/dpdk/lib/librte_reorder")
                                     (concat root "deps/dpdk/lib/librte_ring")
                                     (concat root "deps/dpdk/lib/librte_sched")
                                     (concat root "deps/dpdk/lib/librte_security")
                                     (concat root "deps/dpdk/lib/librte_table")
                                     (concat root "deps/dpdk/lib/librte_timer")
                                     (concat root "deps/dpdk/lib/librte_vhost")
                                     (concat root "deps/expected")
                                     (concat root "deps/immer")
                                     (concat root "deps/json/single_include")
                                     (concat root "deps/json/single_include/nlohmann")
                                     (concat root "deps/lwip/src/include")
                                     (concat root "deps/pistache/include")
                                     (concat root "src/")
                                     (concat root "src/framework")
                                     (concat root "src/modules")
                                     (concat root "src/modules/packetio/stack/include")
                                     )))))))
