// Code generated by go-swagger; DO NOT EDIT.

package block_generator

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewBulkDeleteBlockFilesParams creates a new BulkDeleteBlockFilesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewBulkDeleteBlockFilesParams() *BulkDeleteBlockFilesParams {
	return &BulkDeleteBlockFilesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewBulkDeleteBlockFilesParamsWithTimeout creates a new BulkDeleteBlockFilesParams object
// with the ability to set a timeout on a request.
func NewBulkDeleteBlockFilesParamsWithTimeout(timeout time.Duration) *BulkDeleteBlockFilesParams {
	return &BulkDeleteBlockFilesParams{
		timeout: timeout,
	}
}

// NewBulkDeleteBlockFilesParamsWithContext creates a new BulkDeleteBlockFilesParams object
// with the ability to set a context for a request.
func NewBulkDeleteBlockFilesParamsWithContext(ctx context.Context) *BulkDeleteBlockFilesParams {
	return &BulkDeleteBlockFilesParams{
		Context: ctx,
	}
}

// NewBulkDeleteBlockFilesParamsWithHTTPClient creates a new BulkDeleteBlockFilesParams object
// with the ability to set a custom HTTPClient for a request.
func NewBulkDeleteBlockFilesParamsWithHTTPClient(client *http.Client) *BulkDeleteBlockFilesParams {
	return &BulkDeleteBlockFilesParams{
		HTTPClient: client,
	}
}

/* BulkDeleteBlockFilesParams contains all the parameters to send to the API endpoint
   for the bulk delete block files operation.

   Typically these are written to a http.Request.
*/
type BulkDeleteBlockFilesParams struct {

	/* Delete.

	   Bulk delete
	*/
	Delete BulkDeleteBlockFilesBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the bulk delete block files params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BulkDeleteBlockFilesParams) WithDefaults() *BulkDeleteBlockFilesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the bulk delete block files params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BulkDeleteBlockFilesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the bulk delete block files params
func (o *BulkDeleteBlockFilesParams) WithTimeout(timeout time.Duration) *BulkDeleteBlockFilesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the bulk delete block files params
func (o *BulkDeleteBlockFilesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the bulk delete block files params
func (o *BulkDeleteBlockFilesParams) WithContext(ctx context.Context) *BulkDeleteBlockFilesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the bulk delete block files params
func (o *BulkDeleteBlockFilesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the bulk delete block files params
func (o *BulkDeleteBlockFilesParams) WithHTTPClient(client *http.Client) *BulkDeleteBlockFilesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the bulk delete block files params
func (o *BulkDeleteBlockFilesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDelete adds the delete to the bulk delete block files params
func (o *BulkDeleteBlockFilesParams) WithDelete(delete BulkDeleteBlockFilesBody) *BulkDeleteBlockFilesParams {
	o.SetDelete(delete)
	return o
}

// SetDelete adds the delete to the bulk delete block files params
func (o *BulkDeleteBlockFilesParams) SetDelete(delete BulkDeleteBlockFilesBody) {
	o.Delete = delete
}

// WriteToRequest writes these params to a swagger request
func (o *BulkDeleteBlockFilesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Delete); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
