// Code generated by go-swagger; DO NOT EDIT.

package block_generator

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/spirent/openperf/api/client/golang/models"
)

// NewCreateBlockFileParams creates a new CreateBlockFileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateBlockFileParams() *CreateBlockFileParams {
	return &CreateBlockFileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateBlockFileParamsWithTimeout creates a new CreateBlockFileParams object
// with the ability to set a timeout on a request.
func NewCreateBlockFileParamsWithTimeout(timeout time.Duration) *CreateBlockFileParams {
	return &CreateBlockFileParams{
		timeout: timeout,
	}
}

// NewCreateBlockFileParamsWithContext creates a new CreateBlockFileParams object
// with the ability to set a context for a request.
func NewCreateBlockFileParamsWithContext(ctx context.Context) *CreateBlockFileParams {
	return &CreateBlockFileParams{
		Context: ctx,
	}
}

// NewCreateBlockFileParamsWithHTTPClient creates a new CreateBlockFileParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateBlockFileParamsWithHTTPClient(client *http.Client) *CreateBlockFileParams {
	return &CreateBlockFileParams{
		HTTPClient: client,
	}
}

/* CreateBlockFileParams contains all the parameters to send to the API endpoint
   for the create block file operation.

   Typically these are written to a http.Request.
*/
type CreateBlockFileParams struct {

	/* File.

	   New block file
	*/
	File *models.BlockFile

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create block file params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateBlockFileParams) WithDefaults() *CreateBlockFileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create block file params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateBlockFileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create block file params
func (o *CreateBlockFileParams) WithTimeout(timeout time.Duration) *CreateBlockFileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create block file params
func (o *CreateBlockFileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create block file params
func (o *CreateBlockFileParams) WithContext(ctx context.Context) *CreateBlockFileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create block file params
func (o *CreateBlockFileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create block file params
func (o *CreateBlockFileParams) WithHTTPClient(client *http.Client) *CreateBlockFileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create block file params
func (o *CreateBlockFileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFile adds the file to the create block file params
func (o *CreateBlockFileParams) WithFile(file *models.BlockFile) *CreateBlockFileParams {
	o.SetFile(file)
	return o
}

// SetFile adds the file to the create block file params
func (o *CreateBlockFileParams) SetFile(file *models.BlockFile) {
	o.File = file
}

// WriteToRequest writes these params to a swagger request
func (o *CreateBlockFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.File != nil {
		if err := r.SetBodyParam(o.File); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
