// Code generated by go-swagger; DO NOT EDIT.

package packet_captures

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewBulkStopPacketCapturesParams creates a new BulkStopPacketCapturesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewBulkStopPacketCapturesParams() *BulkStopPacketCapturesParams {
	return &BulkStopPacketCapturesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewBulkStopPacketCapturesParamsWithTimeout creates a new BulkStopPacketCapturesParams object
// with the ability to set a timeout on a request.
func NewBulkStopPacketCapturesParamsWithTimeout(timeout time.Duration) *BulkStopPacketCapturesParams {
	return &BulkStopPacketCapturesParams{
		timeout: timeout,
	}
}

// NewBulkStopPacketCapturesParamsWithContext creates a new BulkStopPacketCapturesParams object
// with the ability to set a context for a request.
func NewBulkStopPacketCapturesParamsWithContext(ctx context.Context) *BulkStopPacketCapturesParams {
	return &BulkStopPacketCapturesParams{
		Context: ctx,
	}
}

// NewBulkStopPacketCapturesParamsWithHTTPClient creates a new BulkStopPacketCapturesParams object
// with the ability to set a custom HTTPClient for a request.
func NewBulkStopPacketCapturesParamsWithHTTPClient(client *http.Client) *BulkStopPacketCapturesParams {
	return &BulkStopPacketCapturesParams{
		HTTPClient: client,
	}
}

/* BulkStopPacketCapturesParams contains all the parameters to send to the API endpoint
   for the bulk stop packet captures operation.

   Typically these are written to a http.Request.
*/
type BulkStopPacketCapturesParams struct {

	/* Stop.

	   Bulk stop
	*/
	Stop BulkStopPacketCapturesBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the bulk stop packet captures params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BulkStopPacketCapturesParams) WithDefaults() *BulkStopPacketCapturesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the bulk stop packet captures params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BulkStopPacketCapturesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the bulk stop packet captures params
func (o *BulkStopPacketCapturesParams) WithTimeout(timeout time.Duration) *BulkStopPacketCapturesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the bulk stop packet captures params
func (o *BulkStopPacketCapturesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the bulk stop packet captures params
func (o *BulkStopPacketCapturesParams) WithContext(ctx context.Context) *BulkStopPacketCapturesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the bulk stop packet captures params
func (o *BulkStopPacketCapturesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the bulk stop packet captures params
func (o *BulkStopPacketCapturesParams) WithHTTPClient(client *http.Client) *BulkStopPacketCapturesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the bulk stop packet captures params
func (o *BulkStopPacketCapturesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithStop adds the stop to the bulk stop packet captures params
func (o *BulkStopPacketCapturesParams) WithStop(stop BulkStopPacketCapturesBody) *BulkStopPacketCapturesParams {
	o.SetStop(stop)
	return o
}

// SetStop adds the stop to the bulk stop packet captures params
func (o *BulkStopPacketCapturesParams) SetStop(stop BulkStopPacketCapturesBody) {
	o.Stop = stop
}

// WriteToRequest writes these params to a swagger request
func (o *BulkStopPacketCapturesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Stop); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
