// Code generated by go-swagger; DO NOT EDIT.

package packet_captures

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeletePacketCaptureParams creates a new DeletePacketCaptureParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeletePacketCaptureParams() *DeletePacketCaptureParams {
	return &DeletePacketCaptureParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeletePacketCaptureParamsWithTimeout creates a new DeletePacketCaptureParams object
// with the ability to set a timeout on a request.
func NewDeletePacketCaptureParamsWithTimeout(timeout time.Duration) *DeletePacketCaptureParams {
	return &DeletePacketCaptureParams{
		timeout: timeout,
	}
}

// NewDeletePacketCaptureParamsWithContext creates a new DeletePacketCaptureParams object
// with the ability to set a context for a request.
func NewDeletePacketCaptureParamsWithContext(ctx context.Context) *DeletePacketCaptureParams {
	return &DeletePacketCaptureParams{
		Context: ctx,
	}
}

// NewDeletePacketCaptureParamsWithHTTPClient creates a new DeletePacketCaptureParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeletePacketCaptureParamsWithHTTPClient(client *http.Client) *DeletePacketCaptureParams {
	return &DeletePacketCaptureParams{
		HTTPClient: client,
	}
}

/* DeletePacketCaptureParams contains all the parameters to send to the API endpoint
   for the delete packet capture operation.

   Typically these are written to a http.Request.
*/
type DeletePacketCaptureParams struct {

	/* ID.

	   Unique resource identifier

	   Format: string
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete packet capture params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeletePacketCaptureParams) WithDefaults() *DeletePacketCaptureParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete packet capture params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeletePacketCaptureParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete packet capture params
func (o *DeletePacketCaptureParams) WithTimeout(timeout time.Duration) *DeletePacketCaptureParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete packet capture params
func (o *DeletePacketCaptureParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete packet capture params
func (o *DeletePacketCaptureParams) WithContext(ctx context.Context) *DeletePacketCaptureParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete packet capture params
func (o *DeletePacketCaptureParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete packet capture params
func (o *DeletePacketCaptureParams) WithHTTPClient(client *http.Client) *DeletePacketCaptureParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete packet capture params
func (o *DeletePacketCaptureParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete packet capture params
func (o *DeletePacketCaptureParams) WithID(id string) *DeletePacketCaptureParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete packet capture params
func (o *DeletePacketCaptureParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePacketCaptureParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
