// Code generated by go-swagger; DO NOT EDIT.

package packet_captures

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPacketCaptureLiveParams creates a new GetPacketCaptureLiveParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPacketCaptureLiveParams() *GetPacketCaptureLiveParams {
	return &GetPacketCaptureLiveParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPacketCaptureLiveParamsWithTimeout creates a new GetPacketCaptureLiveParams object
// with the ability to set a timeout on a request.
func NewGetPacketCaptureLiveParamsWithTimeout(timeout time.Duration) *GetPacketCaptureLiveParams {
	return &GetPacketCaptureLiveParams{
		timeout: timeout,
	}
}

// NewGetPacketCaptureLiveParamsWithContext creates a new GetPacketCaptureLiveParams object
// with the ability to set a context for a request.
func NewGetPacketCaptureLiveParamsWithContext(ctx context.Context) *GetPacketCaptureLiveParams {
	return &GetPacketCaptureLiveParams{
		Context: ctx,
	}
}

// NewGetPacketCaptureLiveParamsWithHTTPClient creates a new GetPacketCaptureLiveParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPacketCaptureLiveParamsWithHTTPClient(client *http.Client) *GetPacketCaptureLiveParams {
	return &GetPacketCaptureLiveParams{
		HTTPClient: client,
	}
}

/* GetPacketCaptureLiveParams contains all the parameters to send to the API endpoint
   for the get packet capture live operation.

   Typically these are written to a http.Request.
*/
type GetPacketCaptureLiveParams struct {

	/* ID.

	   Unique resource identifier

	   Format: string
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get packet capture live params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPacketCaptureLiveParams) WithDefaults() *GetPacketCaptureLiveParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get packet capture live params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPacketCaptureLiveParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get packet capture live params
func (o *GetPacketCaptureLiveParams) WithTimeout(timeout time.Duration) *GetPacketCaptureLiveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get packet capture live params
func (o *GetPacketCaptureLiveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get packet capture live params
func (o *GetPacketCaptureLiveParams) WithContext(ctx context.Context) *GetPacketCaptureLiveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get packet capture live params
func (o *GetPacketCaptureLiveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get packet capture live params
func (o *GetPacketCaptureLiveParams) WithHTTPClient(client *http.Client) *GetPacketCaptureLiveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get packet capture live params
func (o *GetPacketCaptureLiveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get packet capture live params
func (o *GetPacketCaptureLiveParams) WithID(id string) *GetPacketCaptureLiveParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get packet capture live params
func (o *GetPacketCaptureLiveParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetPacketCaptureLiveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
