// Code generated by go-swagger; DO NOT EDIT.

package network_generator

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/spirent/openperf/api/client/golang/models"
)

// NewToggleNetworkGeneratorsParams creates a new ToggleNetworkGeneratorsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewToggleNetworkGeneratorsParams() *ToggleNetworkGeneratorsParams {
	return &ToggleNetworkGeneratorsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewToggleNetworkGeneratorsParamsWithTimeout creates a new ToggleNetworkGeneratorsParams object
// with the ability to set a timeout on a request.
func NewToggleNetworkGeneratorsParamsWithTimeout(timeout time.Duration) *ToggleNetworkGeneratorsParams {
	return &ToggleNetworkGeneratorsParams{
		timeout: timeout,
	}
}

// NewToggleNetworkGeneratorsParamsWithContext creates a new ToggleNetworkGeneratorsParams object
// with the ability to set a context for a request.
func NewToggleNetworkGeneratorsParamsWithContext(ctx context.Context) *ToggleNetworkGeneratorsParams {
	return &ToggleNetworkGeneratorsParams{
		Context: ctx,
	}
}

// NewToggleNetworkGeneratorsParamsWithHTTPClient creates a new ToggleNetworkGeneratorsParams object
// with the ability to set a custom HTTPClient for a request.
func NewToggleNetworkGeneratorsParamsWithHTTPClient(client *http.Client) *ToggleNetworkGeneratorsParams {
	return &ToggleNetworkGeneratorsParams{
		HTTPClient: client,
	}
}

/* ToggleNetworkGeneratorsParams contains all the parameters to send to the API endpoint
   for the toggle network generators operation.

   Typically these are written to a http.Request.
*/
type ToggleNetworkGeneratorsParams struct {

	/* Toggle.

	   Network generator toggle
	*/
	Toggle *models.ToggleNetworkGeneratorsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the toggle network generators params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ToggleNetworkGeneratorsParams) WithDefaults() *ToggleNetworkGeneratorsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the toggle network generators params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ToggleNetworkGeneratorsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the toggle network generators params
func (o *ToggleNetworkGeneratorsParams) WithTimeout(timeout time.Duration) *ToggleNetworkGeneratorsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the toggle network generators params
func (o *ToggleNetworkGeneratorsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the toggle network generators params
func (o *ToggleNetworkGeneratorsParams) WithContext(ctx context.Context) *ToggleNetworkGeneratorsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the toggle network generators params
func (o *ToggleNetworkGeneratorsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the toggle network generators params
func (o *ToggleNetworkGeneratorsParams) WithHTTPClient(client *http.Client) *ToggleNetworkGeneratorsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the toggle network generators params
func (o *ToggleNetworkGeneratorsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithToggle adds the toggle to the toggle network generators params
func (o *ToggleNetworkGeneratorsParams) WithToggle(toggle *models.ToggleNetworkGeneratorsRequest) *ToggleNetworkGeneratorsParams {
	o.SetToggle(toggle)
	return o
}

// SetToggle adds the toggle to the toggle network generators params
func (o *ToggleNetworkGeneratorsParams) SetToggle(toggle *models.ToggleNetworkGeneratorsRequest) {
	o.Toggle = toggle
}

// WriteToRequest writes these params to a swagger request
func (o *ToggleNetworkGeneratorsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Toggle != nil {
		if err := r.SetBodyParam(o.Toggle); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
