#ifndef _OP_MEMORY_IO_PATTERN_HPP_
#define _OP_MEMORY_IO_PATTERN_HPP_

enum io_pattern {
    GENERATOR_PATTERN_NONE = 0,
    GENERATOR_PATTERN_RANDOM,
    GENERATOR_PATTERN_SEQUENTIAL,
    GENERATOR_PATTERN_REVERSE,
    GENERATOR_PATTERN_MAX,
};

#endif // _OP_MEMORY_IO_PATTERN_HPP_
