# coding: utf-8

"""
    OpenPerf API

    REST API interface for OpenPerf  # noqa: E501

    OpenAPI spec version: 1
    Contact: support@spirent.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PacketAnalyzerFlowCountersPrbs(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bit_errors': 'int',
        'frame_errors': 'int',
        'octets': 'int'
    }

    attribute_map = {
        'bit_errors': 'bit_errors',
        'frame_errors': 'frame_errors',
        'octets': 'octets'
    }

    def __init__(self, bit_errors=None, frame_errors=None, octets=None):  # noqa: E501
        """PacketAnalyzerFlowCountersPrbs - a model defined in Swagger"""  # noqa: E501

        self._bit_errors = None
        self._frame_errors = None
        self._octets = None
        self.discriminator = None

        self.bit_errors = bit_errors
        if frame_errors is not None:
            self.frame_errors = frame_errors
        self.octets = octets

    @property
    def bit_errors(self):
        """Gets the bit_errors of this PacketAnalyzerFlowCountersPrbs.  # noqa: E501

        Number of PRBS bit errors detected  # noqa: E501

        :return: The bit_errors of this PacketAnalyzerFlowCountersPrbs.  # noqa: E501
        :rtype: int
        """
        return self._bit_errors

    @bit_errors.setter
    def bit_errors(self, bit_errors):
        """Sets the bit_errors of this PacketAnalyzerFlowCountersPrbs.

        Number of PRBS bit errors detected  # noqa: E501

        :param bit_errors: The bit_errors of this PacketAnalyzerFlowCountersPrbs.  # noqa: E501
        :type: int
        """
        self._bit_errors = bit_errors

    @property
    def frame_errors(self):
        """Gets the frame_errors of this PacketAnalyzerFlowCountersPrbs.  # noqa: E501

        Number of packets with PRBS bit errors detected  # noqa: E501

        :return: The frame_errors of this PacketAnalyzerFlowCountersPrbs.  # noqa: E501
        :rtype: int
        """
        return self._frame_errors

    @frame_errors.setter
    def frame_errors(self, frame_errors):
        """Sets the frame_errors of this PacketAnalyzerFlowCountersPrbs.

        Number of packets with PRBS bit errors detected  # noqa: E501

        :param frame_errors: The frame_errors of this PacketAnalyzerFlowCountersPrbs.  # noqa: E501
        :type: int
        """
        self._frame_errors = frame_errors

    @property
    def octets(self):
        """Gets the octets of this PacketAnalyzerFlowCountersPrbs.  # noqa: E501

        Number of PRBS octets checked  # noqa: E501

        :return: The octets of this PacketAnalyzerFlowCountersPrbs.  # noqa: E501
        :rtype: int
        """
        return self._octets

    @octets.setter
    def octets(self, octets):
        """Sets the octets of this PacketAnalyzerFlowCountersPrbs.

        Number of PRBS octets checked  # noqa: E501

        :param octets: The octets of this PacketAnalyzerFlowCountersPrbs.  # noqa: E501
        :type: int
        """
        self._octets = octets

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PacketAnalyzerFlowCountersPrbs, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PacketAnalyzerFlowCountersPrbs):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
