# coding: utf-8

"""
    Inception Core API

    REST API interface to the Inception Core  # noqa: E501

    OpenAPI spec version: 1
    Contact: support@spirent.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from client.models.port_config import PortConfig  # noqa: F401,E501
from client.models.port_stats import PortStats  # noqa: F401,E501
from client.models.port_status import PortStatus  # noqa: F401,E501


class Port(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'kind': 'str',
        'config': 'PortConfig',
        'status': 'PortStatus',
        'stats': 'PortStats'
    }

    attribute_map = {
        'id': 'id',
        'kind': 'kind',
        'config': 'config',
        'status': 'status',
        'stats': 'stats'
    }

    def __init__(self, id=None, kind=None, config=None, status=None, stats=None):  # noqa: E501
        """Port - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._kind = None
        self._config = None
        self._status = None
        self._stats = None
        self.discriminator = None

        self.id = id
        self.kind = kind
        self.config = config
        self.status = status
        self.stats = stats

    @property
    def id(self):
        """Gets the id of this Port.  # noqa: E501

        Unique port identifier  # noqa: E501

        :return: The id of this Port.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Port.

        Unique port identifier  # noqa: E501

        :param id: The id of this Port.  # noqa: E501
        :type: str
        """
        self._id = id

    @property
    def kind(self):
        """Gets the kind of this Port.  # noqa: E501

        Port kind  # noqa: E501

        :return: The kind of this Port.  # noqa: E501
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this Port.

        Port kind  # noqa: E501

        :param kind: The kind of this Port.  # noqa: E501
        :type: str
        """
        self._kind = kind

    @property
    def config(self):
        """Gets the config of this Port.  # noqa: E501


        :return: The config of this Port.  # noqa: E501
        :rtype: PortConfig
        """
        return self._config

    @config.setter
    def config(self, config):
        """Sets the config of this Port.


        :param config: The config of this Port.  # noqa: E501
        :type: PortConfig
        """
        self._config = config

    @property
    def status(self):
        """Gets the status of this Port.  # noqa: E501


        :return: The status of this Port.  # noqa: E501
        :rtype: PortStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Port.


        :param status: The status of this Port.  # noqa: E501
        :type: PortStatus
        """
        self._status = status

    @property
    def stats(self):
        """Gets the stats of this Port.  # noqa: E501


        :return: The stats of this Port.  # noqa: E501
        :rtype: PortStats
        """
        return self._stats

    @stats.setter
    def stats(self, stats):
        """Sets the stats of this Port.


        :param stats: The stats of this Port.  # noqa: E501
        :type: PortStats
        """
        self._stats = stats

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Port):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
