# coding: utf-8

"""
    OpenPerf API

    REST API interface for OpenPerf  # noqa: E501

    OpenAPI spec version: 1
    Contact: support@spirent.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class TimeSourceStatsSystem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'poll_count': 'int',
        'poll_period': 'int'
    }

    attribute_map = {
        'poll_count': 'poll_count',
        'poll_period': 'poll_period'
    }

    def __init__(self, poll_count=None, poll_period=None):  # noqa: E501
        """TimeSourceStatsSystem - a model defined in Swagger"""  # noqa: E501

        self._poll_count = None
        self._poll_period = None
        self.discriminator = None

        self.poll_count = poll_count
        self.poll_period = poll_period

    @property
    def poll_count(self):
        """Gets the poll_count of this TimeSourceStatsSystem.  # noqa: E501

        Number of times the system clock has been polled  # noqa: E501

        :return: The poll_count of this TimeSourceStatsSystem.  # noqa: E501
        :rtype: int
        """
        return self._poll_count

    @poll_count.setter
    def poll_count(self, poll_count):
        """Sets the poll_count of this TimeSourceStatsSystem.

        Number of times the system clock has been polled  # noqa: E501

        :param poll_count: The poll_count of this TimeSourceStatsSystem.  # noqa: E501
        :type: int
        """
        self._poll_count = poll_count

    @property
    def poll_period(self):
        """Gets the poll_period of this TimeSourceStatsSystem.  # noqa: E501

        Current system poll period, in seconds  # noqa: E501

        :return: The poll_period of this TimeSourceStatsSystem.  # noqa: E501
        :rtype: int
        """
        return self._poll_period

    @poll_period.setter
    def poll_period(self, poll_period):
        """Sets the poll_period of this TimeSourceStatsSystem.

        Current system poll period, in seconds  # noqa: E501

        :param poll_period: The poll_period of this TimeSourceStatsSystem.  # noqa: E501
        :type: int
        """
        self._poll_period = poll_period

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TimeSourceStatsSystem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TimeSourceStatsSystem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
