# coding: utf-8

"""
    OpenPerf API

    REST API interface for OpenPerf  # noqa: E501

    OpenAPI spec version: 1
    Contact: support@spirent.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class TrafficProtocolIpv6Modifier(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'list': 'list[str]',
        'sequence': 'TrafficProtocolIpv6ModifierSequence'
    }

    attribute_map = {
        'list': 'list',
        'sequence': 'sequence'
    }

    def __init__(self, list=None, sequence=None):  # noqa: E501
        """TrafficProtocolIpv6Modifier - a model defined in Swagger"""  # noqa: E501

        self._list = None
        self._sequence = None
        self.discriminator = None

        if list is not None:
            self.list = list
        if sequence is not None:
            self.sequence = sequence

    @property
    def list(self):
        """Gets the list of this TrafficProtocolIpv6Modifier.  # noqa: E501

        List of IPv6 addresses  # noqa: E501

        :return: The list of this TrafficProtocolIpv6Modifier.  # noqa: E501
        :rtype: list[str]
        """
        return self._list

    @list.setter
    def list(self, list):
        """Sets the list of this TrafficProtocolIpv6Modifier.

        List of IPv6 addresses  # noqa: E501

        :param list: The list of this TrafficProtocolIpv6Modifier.  # noqa: E501
        :type: list[str]
        """
        self._list = list

    @property
    def sequence(self):
        """Gets the sequence of this TrafficProtocolIpv6Modifier.  # noqa: E501


        :return: The sequence of this TrafficProtocolIpv6Modifier.  # noqa: E501
        :rtype: TrafficProtocolIpv6ModifierSequence
        """
        return self._sequence

    @sequence.setter
    def sequence(self, sequence):
        """Sets the sequence of this TrafficProtocolIpv6Modifier.


        :param sequence: The sequence of this TrafficProtocolIpv6Modifier.  # noqa: E501
        :type: TrafficProtocolIpv6ModifierSequence
        """
        self._sequence = sequence

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TrafficProtocolIpv6Modifier, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TrafficProtocolIpv6Modifier):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
