// Code generated by go-swagger; DO NOT EDIT.

package time_sync

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/Spirent/openperf/targets/spiperf/openperf/v1/models"
)

// CreateTimeSourceReader is a Reader for the CreateTimeSource structure.
type CreateTimeSourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateTimeSourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateTimeSourceCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateTimeSourceCreated creates a CreateTimeSourceCreated with default headers values
func NewCreateTimeSourceCreated() *CreateTimeSourceCreated {
	return &CreateTimeSourceCreated{}
}

/*CreateTimeSourceCreated handles this case with default header values.

Success
*/
type CreateTimeSourceCreated struct {
	Payload *models.TimeSource
}

func (o *CreateTimeSourceCreated) Error() string {
	return fmt.Sprintf("[POST /time-sources][%d] createTimeSourceCreated  %+v", 201, o.Payload)
}

func (o *CreateTimeSourceCreated) GetPayload() *models.TimeSource {
	return o.Payload
}

func (o *CreateTimeSourceCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TimeSource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
