swagger: "2.0"

info:
  title: OpenPerf API
  description: REST API interface for OpenPerf
  termsOfService: TODO
  contact:
    name: "Spirent, Inc."
    url: "http://spirent.com"
    email: "support@spirent.com"
  license:
    name: "Apache-2.0"
    url: "https://www.apache.org/licenses/LICENSE-2.0.txt"
  version: "1"

schemes:
  - http
  - https

host: localhost

produces:
  - application/json

consumes:
  - application/json

parameters:
  id:
    name: id
    in: path
    description: Unique resource identifier
    type: string
    format: string
    required: true

tags:
  - name: Interfaces
  - name: Modules
  - name: Ports
  - name: Stacks
  - name: TimeSync

basePath: /

paths:
  ###
  # Framework paths
  ###
  /modules:
    get:
      operationId: ListModules
      tags:
        - Modules
      summary: List Modules
      description: The `modules` endpoint returns all loaded modules.
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/Module"

  /modules/{id}:
    get:
      operationId: GetModule
      tags:
        - Modules
      summary: Get a module
      description: Returns a module, by id.
      parameters:
        - $ref: "#/parameters/id"
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/Module"

  ###
  # PacketIO Paths
  ###
  /interfaces:
    $ref: ./modules/packetio.yaml#/paths/~1interfaces

  /interfaces/{id}:
    $ref: ./modules/packetio.yaml#/paths/~1interfaces~1{id}

  /interfaces/x/bulk-create:
    $ref: ./modules/packetio.yaml#/paths/~1interfaces~1x~1bulk-create

  /interfaces/x/bulk-delete:
    $ref: ./modules/packetio.yaml#/paths/~1interfaces~1x~1bulk-delete

  /ports:
    $ref: ./modules/packetio.yaml#/paths/~1ports

  /ports/{id}:
    $ref: ./modules/packetio.yaml#/paths/~1ports~1{id}

  /stacks:
    $ref: ./modules/packetio.yaml#/paths/~1stacks

  /stacks/{id}:
    $ref: ./modules/packetio.yaml#/paths/~1stacks~1{id}

  ###
  # Timesync paths
  ###
  /time-counters:
    $ref: ./modules/timesync.yaml#/paths/~1time-counters

  /time-counters/{id}:
    $ref: ./modules/timesync.yaml#/paths/~1time-counters~1{id}

  /time-keeper:
    $ref: ./modules/timesync.yaml#/paths/~1time-keeper

  /time-sources:
    $ref: ./modules/timesync.yaml#/paths/~1time-sources

  /time-sources/{id}:
    $ref: ./modules/timesync.yaml#/paths/~1time-sources~1{id}

definitions:
  Module:
    type: object
    description: A test module that has been statically linked or dynamically loaded into the process
    properties:
      id:
        type: string
        description: Unique module identifier
        readOnly: true
      description:
        type: string
        description: Description of module functionality
        readOnly: true
      version:
        $ref: "#/definitions/ModuleVersion"
      linkage:
        type: string
        description: Linkage type
        readOnly: true
        enum:
          - static
          - dynamic
      path:
        type: string
        description: Path to module binary (dynamically-loaded modules only).
        readOnly: true
    required:
      - id
      - description
      - version
      - linkage

  ModuleVersion:
    type: object
    description: Module version information
    properties:
      version:
        type: integer
        description: Module version number
        format: int32
        readOnly: true
      build_number:
        type: string
        description: Module build number
        readOnly: true
      build_date:
        type: string
        description: Module build date
        format: date-time
        readOnly: true
      source_commit:
        type: string
        description: Module version control revision
        readOnly: true
    required:
      - version
