swagger: "2.0"

info:
  title: OpenPerf API
  description: REST API interface for OpenPerf
  termsOfService: TODO
  contact:
    name: "Spirent, Inc."
    url: "http://spirent.com"
    email: "support@spirent.com"
  license:
    name: "Apache-2.0"
    url: "https://www.apache.org/licenses/LICENSE-2.0.txt"
  version: "1"

schemes:
  - http
  - https

host: localhost

produces:
  - application/json

consumes:
  - application/json

parameters:
  id:
    name: id
    in: path
    description: Unique resource identifier
    type: string
    format: string
    required: true

  dynamic_results:
    $ref: ./modules/dynamic.yaml#/parameters/dynamic_results

tags:
  - name: Interfaces
  - name: Modules
  - name: PacketGenerators
  - name: Ports
  - name: Stacks
  - name: TimeSync
  - name: BlockGenerator
  - name: MemoryGenerator
  - name: CpuGenerator

basePath: /

paths:
  ###
  # Framework paths
  ###
  /modules:
    get:
      operationId: ListModules
      tags:
        - Modules
      summary: List Modules
      description: The `modules` endpoint returns all loaded modules.
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/Module"

  /modules/{id}:
    get:
      operationId: GetModule
      tags:
        - Modules
      summary: Get a module
      description: Returns a module, by id.
      parameters:
        - $ref: "#/parameters/id"
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/Module"

  ###
  # PacketIO Paths
  ###
  /interfaces:
    $ref: ./modules/packetio.yaml#/paths/~1interfaces

  /interfaces/{id}:
    $ref: ./modules/packetio.yaml#/paths/~1interfaces~1{id}

  /interfaces/x/bulk-create:
    $ref: ./modules/packetio.yaml#/paths/~1interfaces~1x~1bulk-create

  /interfaces/x/bulk-delete:
    $ref: ./modules/packetio.yaml#/paths/~1interfaces~1x~1bulk-delete

  /ports:
    $ref: ./modules/packetio.yaml#/paths/~1ports

  /ports/{id}:
    $ref: ./modules/packetio.yaml#/paths/~1ports~1{id}

  /stacks:
    $ref: ./modules/packetio.yaml#/paths/~1stacks

  /stacks/{id}:
    $ref: ./modules/packetio.yaml#/paths/~1stacks~1{id}

  ###
  # Packet Analyzer Paths
  ###
  /packet/analyzers:
    $ref: ./modules/packet/analyzer.yaml#/paths/~1analyzers

  /packet/analyzers/{id}:
    $ref: ./modules/packet/analyzer.yaml#/paths/~1analyzers~1{id}

  /packet/analyzers/{id}/reset:
    $ref: ./modules/packet/analyzer.yaml#/paths/~1analyzers~1{id}~1reset

  /packet/analyzers/{id}/start:
    $ref: ./modules/packet/analyzer.yaml#/paths/~1analyzers~1{id}~1start

  /packet/analyzers/{id}/stop:
    $ref: ./modules/packet/analyzer.yaml#/paths/~1analyzers~1{id}~1stop

  /packet/analyzers/x/bulk-create:
    $ref: ./modules/packet/analyzer.yaml#/paths/~1analyzers~1x~1bulk-create

  /packet/analyzers/x/bulk-delete:
    $ref: ./modules/packet/analyzer.yaml#/paths/~1analyzers~1x~1bulk-delete

  /packet/analyzers/x/bulk-start:
    $ref: ./modules/packet/analyzer.yaml#/paths/~1analyzers~1x~1bulk-start

  /packet/analyzers/x/bulk-stop:
    $ref: ./modules/packet/analyzer.yaml#/paths/~1analyzers~1x~1bulk-stop

  /packet/analyzer-results:
    $ref: ./modules/packet/analyzer.yaml#/paths/~1analyzer-results

  /packet/analyzer-results/{id}:
    $ref: ./modules/packet/analyzer.yaml#/paths/~1analyzer-results~1{id}

  /packet/rx-flows:
    $ref: ./modules/packet/analyzer.yaml#/paths/~1rx-flows

  /packet/rx-flows/{id}:
    $ref: ./modules/packet/analyzer.yaml#/paths/~1rx-flows~1{id}

  ###
  # Packet Capture Paths
  ###
  /packet/captures:
    $ref: ./modules/packet/capture.yaml#/paths/~1captures

  /packet/captures/{id}:
    $ref: ./modules/packet/capture.yaml#/paths/~1captures~1{id}

  /packet/captures/{id}/start:
    $ref: ./modules/packet/capture.yaml#/paths/~1captures~1{id}~1start

  /packet/captures/{id}/stop:
    $ref: ./modules/packet/capture.yaml#/paths/~1captures~1{id}~1stop

  /packet/captures/x/bulk-create:
    $ref: ./modules/packet/capture.yaml#/paths/~1captures~1x~1bulk-create

  /packet/captures/x/bulk-delete:
    $ref: ./modules/packet/capture.yaml#/paths/~1captures~1x~1bulk-delete

  /packet/captures/x/bulk-start:
    $ref: ./modules/packet/capture.yaml#/paths/~1captures~1x~1bulk-start

  /packet/captures/x/bulk-stop:
    $ref: ./modules/packet/capture.yaml#/paths/~1captures~1x~1bulk-stop

  /packet/captures/x/merge:
    $ref: ./modules/packet/capture.yaml#/paths/~1captures~1x~1merge

  /packet/capture-results:
    $ref: ./modules/packet/capture.yaml#/paths/~1capture-results

  /packet/capture-results/{id}:
    $ref: ./modules/packet/capture.yaml#/paths/~1capture-results~1{id}

  /packet/capture-results/{id}/pcap:
    $ref: ./modules/packet/capture.yaml#/paths/~1capture-results~1{id}~1pcap

  /packet/capture-results/{id}/live:
    $ref: ./modules/packet/capture.yaml#/paths/~1capture-results~1{id}~1live

  ###
  # Packet Generator Paths
  ###
  /packet/generators:
    $ref: ./modules/packet/generator.yaml#/paths/~1generators

  /packet/generators/{id}:
    $ref: ./modules/packet/generator.yaml#/paths/~1generators~1{id}

  /packet/generators/{id}/start:
    $ref: ./modules/packet/generator.yaml#/paths/~1generators~1{id}~1start

  /packet/generators/{id}/stop:
    $ref: ./modules/packet/generator.yaml#/paths/~1generators~1{id}~1stop

  /packet/generators/x/bulk-create:
    $ref: ./modules/packet/generator.yaml#/paths/~1generators~1x~1bulk-create

  /packet/generators/x/bulk-delete:
    $ref: ./modules/packet/generator.yaml#/paths/~1generators~1x~1bulk-delete

  /packet/generators/x/bulk-start:
    $ref: ./modules/packet/generator.yaml#/paths/~1generators~1x~1bulk-start

  /packet/generators/x/bulk-stop:
    $ref: ./modules/packet/generator.yaml#/paths/~1generators~1x~1bulk-stop

  /packet/generators/x/toggle:
    $ref: ./modules/packet/generator.yaml#/paths/~1generators~1x~1toggle

  /packet/generator-results:
    $ref: ./modules/packet/generator.yaml#/paths/~1generator-results

  /packet/generator-results/{id}:
    $ref: ./modules/packet/generator.yaml#/paths/~1generator-results~1{id}

  /packet/tx-flows:
    $ref: ./modules/packet/generator.yaml#/paths/~1tx-flows

  /packet/tx-flows/{id}:
    $ref: ./modules/packet/generator.yaml#/paths/~1tx-flows~1{id}

  ###
  # Timesync paths
  ###
  /time-counters:
    $ref: ./modules/timesync.yaml#/paths/~1time-counters

  /time-counters/{id}:
    $ref: ./modules/timesync.yaml#/paths/~1time-counters~1{id}

  /time-keeper:
    $ref: ./modules/timesync.yaml#/paths/~1time-keeper

  /time-sources:
    $ref: ./modules/timesync.yaml#/paths/~1time-sources

  /time-sources/{id}:
    $ref: ./modules/timesync.yaml#/paths/~1time-sources~1{id}

  ###
  # Block paths
  ###
  /block-devices:
    $ref: ./modules/block.yaml#/paths/~1block-devices

  /block-devices/{id}:
    $ref: ./modules/block.yaml#/paths/~1block-devices~1{id}

  /block-files:
    $ref: ./modules/block.yaml#/paths/~1block-files

  /block-files/{id}:
    $ref: ./modules/block.yaml#/paths/~1block-files~1{id}

  /block-files/x/bulk-create:
    $ref: ./modules/block.yaml#/paths/~1block-files~1x~1bulk-create

  /block-files/x/bulk-delete:
    $ref: ./modules/block.yaml#/paths/~1block-files~1x~1bulk-delete

  /block-generators:
    $ref: ./modules/block.yaml#/paths/~1block-generators

  /block-generators/{id}:
    $ref: ./modules/block.yaml#/paths/~1block-generators~1{id}

  /block-generators/x/bulk-create:
    $ref: ./modules/block.yaml#/paths/~1block-generators~1x~1bulk-create

  /block-generators/x/bulk-delete:
    $ref: ./modules/block.yaml#/paths/~1block-generators~1x~1bulk-delete

  /block-generators/{id}/start:
    $ref: ./modules/block.yaml#/paths/~1block-generators~1{id}~1start

  /block-generators/{id}/stop:
    $ref: ./modules/block.yaml#/paths/~1block-generators~1{id}~1stop

  /block-generators/x/bulk-start:
    $ref: ./modules/block.yaml#/paths/~1block-generators~1x~1bulk-start

  /block-generators/x/bulk-stop:
    $ref: ./modules/block.yaml#/paths/~1block-generators~1x~1bulk-stop

  /block-generator-results:
    $ref: ./modules/block.yaml#/paths/~1block-generator-results

  /block-generator-results/{id}:
    $ref: ./modules/block.yaml#/paths/~1block-generator-results~1{id}

  ###
  # Memory paths
  ###
  /memory-generators:
    $ref: ./modules/memory.yaml#/paths/~1memory-generators

  /memory-generators/{id}:
    $ref: ./modules/memory.yaml#/paths/~1memory-generators~1{id}

  /memory-generators/x/bulk-create:
    $ref: ./modules/memory.yaml#/paths/~1memory-generators~1x~1bulk-create

  /memory-generators/x/bulk-delete:
    $ref: ./modules/memory.yaml#/paths/~1memory-generators~1x~1bulk-delete

  /memory-generators/{id}/start:
    $ref: ./modules/memory.yaml#/paths/~1memory-generators~1{id}~1start

  /memory-generators/{id}/stop:
    $ref: ./modules/memory.yaml#/paths/~1memory-generators~1{id}~1stop

  /memory-generators/x/bulk-start:
    $ref: ./modules/memory.yaml#/paths/~1memory-generators~1x~1bulk-start

  /memory-generators/x/bulk-stop:
    $ref: ./modules/memory.yaml#/paths/~1memory-generators~1x~1bulk-stop

  /memory-generator-results:
    $ref: ./modules/memory.yaml#/paths/~1memory-generator-results

  /memory-generator-results/{id}:
    $ref: ./modules/memory.yaml#/paths/~1memory-generator-results~1{id}

  /memory-info:
    $ref: ./modules/memory.yaml#/paths/~1memory-info

  ###
  # CPU paths
  ###
  /cpu-generators:
    $ref: ./modules/cpu.yaml#/paths/~1cpu-generators

  /cpu-generators/{id}:
    $ref: ./modules/cpu.yaml#/paths/~1cpu-generators~1{id}

  /cpu-generators/x/bulk-create:
    $ref: ./modules/cpu.yaml#/paths/~1cpu-generators~1x~1bulk-create

  /cpu-generators/x/bulk-delete:
    $ref: ./modules/cpu.yaml#/paths/~1cpu-generators~1x~1bulk-delete


  /cpu-generators/{id}/start:
    $ref: ./modules/cpu.yaml#/paths/~1cpu-generators~1{id}~1start

  /cpu-generators/{id}/stop:
    $ref: ./modules/cpu.yaml#/paths/~1cpu-generators~1{id}~1stop

  /cpu-generators/x/bulk-start:
    $ref: ./modules/cpu.yaml#/paths/~1cpu-generators~1x~1bulk-start

  /cpu-generators/x/bulk-stop:
    $ref: ./modules/cpu.yaml#/paths/~1cpu-generators~1x~1bulk-stop

  /cpu-generator-results:
    $ref: ./modules/cpu.yaml#/paths/~1cpu-generator-results

  /cpu-generator-results/{id}:
    $ref: ./modules/cpu.yaml#/paths/~1cpu-generator-results~1{id}

  /cpu-info:
    $ref: ./modules/cpu.yaml#/paths/~1cpu-info

definitions:
  Module:
    type: object
    description: A test module that has been statically linked or dynamically loaded into the process
    properties:
      id:
        type: string
        description: Unique module identifier
        readOnly: true
      description:
        type: string
        description: Description of module functionality
        readOnly: true
      version:
        $ref: "#/definitions/ModuleVersion"
      linkage:
        type: string
        description: Linkage type
        readOnly: true
        enum:
          - static
          - dynamic
      path:
        type: string
        description: Path to module binary (dynamically-loaded modules only).
        readOnly: true
    required:
      - version

  ModuleVersion:
    type: object
    description: Module version information
    properties:
      version:
        type: integer
        description: Module version number
        format: int32
        readOnly: true
      build_number:
        type: string
        description: Module build number
        readOnly: true
      build_date:
        type: string
        description: Module build date
        format: date-time
        readOnly: true
      source_commit:
        type: string
        description: Module version control revision
        readOnly: true

  ###
  # Module model definitions go here
  # Note: `swagger-codegen` extracts the model objects from the path definitions,
  # so adding them here isn't strictly necessary.  However, other code generators,
  # e.g. `go-swagger`, are stricter in their interpretation of the swagger
  # specification and require all objects to be explicitly defined.
  ###

  ###
  # PacketIO definitions
  ###
  Interface:
    $ref: ./modules/packetio.yaml#/definitions/Interface

  InterfaceProtocolConfig:
    $ref: ./modules/packetio.yaml#/definitions/InterfaceProtocolConfig

  InterfaceStats:
    $ref: ./modules/packetio.yaml#/definitions/InterfaceStats

  Port:
    $ref: ./modules/packetio.yaml#/definitions/Port

  PortConfig:
    $ref: ./modules/packetio.yaml#/definitions/PortConfig

  PortStats:
    $ref: ./modules/packetio.yaml#/definitions/PortStats

  PortStatus:
    $ref: ./modules/packetio.yaml#/definitions/PortStatus

  Stack:
    $ref: ./modules/packetio.yaml#/definitions/Stack

  StackElementStats:
    $ref: ./modules/packetio.yaml#/definitions/StackElementStats

  StackMemoryStats:
    $ref: ./modules/packetio.yaml#/definitions/StackMemoryStats

  StackProtocolStats:
    $ref: ./modules/packetio.yaml#/definitions/StackProtocolStats

  StackStats:
    $ref: ./modules/packetio.yaml#/definitions/StackStats

  ###
  # Packet Module protocol definitions
  ###
  PacketProtocolEthernet:
    $ref: ./modules/packet/protocol.yaml#/definitions/PacketProtocolEthernet

  PacketProtocolIpv4:
    $ref: ./modules/packet/protocol.yaml#/definitions/PacketProtocolIpv4

  PacketProtocolIpv6:
    $ref: ./modules/packet/protocol.yaml#/definitions/PacketProtocolIpv6

  PacketProtocolMpls:
    $ref: ./modules/packet/protocol.yaml#/definitions/PacketProtocolMpls

  PacketProtocolTcp:
    $ref: ./modules/packet/protocol.yaml#/definitions/PacketProtocolTcp

  PacketProtocolUdp:
    $ref: ./modules/packet/protocol.yaml#/definitions/PacketProtocolUdp

  PacketProtocolVlan:
    $ref: ./modules/packet/protocol.yaml#/definitions/PacketProtocolVlan

  ###
  # Packet Analyzer definitions
  ###
  PacketAnalyzer:
    $ref: ./modules/packet/analyzer.yaml#/definitions/PacketAnalyzer

  PacketAnalyzerConfig:
    $ref: ./modules/packet/analyzer.yaml#/definitions/PacketAnalyzerConfig

  PacketAnalyzerResult:
    $ref: ./modules/packet/analyzer.yaml#/definitions/PacketAnalyzerResult

  PacketAnalyzerProtocolCounters:
    $ref: ./modules/packet/analyzer.yaml#/definitions/PacketAnalyzerProtocolCounters

  PacketAnalyzerFlowSummaryCounters:
    $ref: ./modules/packet/analyzer.yaml#/definitions/PacketAnalyzerFlowSummaryCounters

  PacketAnalyzerFlowCounters:
    $ref: ./modules/packet/analyzer.yaml#/definitions/PacketAnalyzerFlowCounters

  PacketAnalyzerFlowHeader:
    $ref: ./modules/packet/analyzer.yaml#/definitions/PacketAnalyzerFlowHeader

  RxFlow:
    $ref: ./modules/packet/analyzer.yaml#/definitions/RxFlow

  ###
  # Packet Generator definitions
  ###
  PacketGenerator:
    $ref: ./modules/packet/generator.yaml#/definitions/PacketGenerator

  PacketGeneratorConfig:
    $ref: ./modules/packet/generator.yaml#/definitions/PacketGeneratorConfig

  PacketGeneratorFlowCounters:
    $ref: ./modules/packet/generator.yaml#/definitions/PacketGeneratorFlowCounters

  PacketGeneratorProtocolCounters:
    $ref: ./modules/packet/generator.yaml#/definitions/PacketGeneratorProtocolCounters

  PacketGeneratorResult:
    $ref: ./modules/packet/generator.yaml#/definitions/PacketGeneratorResult

  PacketProtocolCustom:
    $ref: ./modules/packet/generator.yaml#/definitions/PacketProtocolCustom

  SpirentSignature:
    $ref: ./modules/packet/generator.yaml#/definitions/SpirentSignature

  TrafficDefinition:
    $ref: ./modules/packet/generator.yaml#/definitions/TrafficDefinition

  TrafficDuration:
    $ref: ./modules/packet/generator.yaml#/definitions/TrafficDuration

  TrafficDurationRemainder:
    $ref: ./modules/packet/generator.yaml#/definitions/TrafficDurationRemainder

  TrafficLength:
    $ref: ./modules/packet/generator.yaml#/definitions/TrafficLength

  TrafficLoad:
    $ref: ./modules/packet/generator.yaml#/definitions/TrafficLoad

  TrafficPacketTemplate:
    $ref: ./modules/packet/generator.yaml#/definitions/TrafficPacketTemplate

  TrafficProtocol:
    $ref: ./modules/packet/generator.yaml#/definitions/TrafficProtocol

  TrafficProtocolModifier:
    $ref: ./modules/packet/generator.yaml#/definitions/TrafficProtocolModifier

  TxFlow:
    $ref: ./modules/packet/generator.yaml#/definitions/TxFlow

  ###
  # Packet Protocol Counter definitions
  ###
  PacketEthernetProtocolCounters:
    $ref: ./modules/packet/protocol_counters.yaml#/definitions/PacketEthernetProtocolCounters

  PacketIpProtocolCounters:
    $ref: ./modules/packet/protocol_counters.yaml#/definitions/PacketIpProtocolCounters

  PacketTransportProtocolCounters:
    $ref: ./modules/packet/protocol_counters.yaml#/definitions/PacketTransportProtocolCounters

  PacketTunnelProtocolCounters:
    $ref: ./modules/packet/protocol_counters.yaml#/definitions/PacketTunnelProtocolCounters

  PacketInnerEthernetProtocolCounters:
    $ref: ./modules/packet/protocol_counters.yaml#/definitions/PacketInnerEthernetProtocolCounters

  PacketInnerIpProtocolCounters:
    $ref: ./modules/packet/protocol_counters.yaml#/definitions/PacketInnerIpProtocolCounters

  PacketInnerTransportProtocolCounters:
    $ref: ./modules/packet/protocol_counters.yaml#/definitions/PacketInnerTransportProtocolCounters

  ###
  # Timesync definitions
  ###
  TimeCounter:
    $ref: ./modules/timesync.yaml#/definitions/TimeCounter

  TimeKeeperState:
    $ref: ./modules/timesync.yaml#/definitions/TimeKeeperState

  TimeKeeperStats:
    $ref: ./modules/timesync.yaml#/definitions/TimeKeeperStats

  TimeKeeper:
    $ref: ./modules/timesync.yaml#/definitions/TimeKeeper

  TimeSourceConfig:
    $ref: ./modules/timesync.yaml#/definitions/TimeSourceConfig

  TimeSourceStats:
    $ref: ./modules/timesync.yaml#/definitions/TimeSourceStats

  TimeSource:
    $ref: ./modules/timesync.yaml#/definitions/TimeSource

  ###
  # Block definitions
  ###
  BlockDevice:
    $ref: ./modules/block.yaml#/definitions/BlockDevice

  BlockFile:
    $ref: ./modules/block.yaml#/definitions/BlockFile

  BlockGenerator:
    $ref: ./modules/block.yaml#/definitions/BlockGenerator

  BlockGeneratorConfig:
    $ref: ./modules/block.yaml#/definitions/BlockGeneratorConfig

  BlockGeneratorResult:
    $ref: ./modules/block.yaml#/definitions/BlockGeneratorResult

  BlockGeneratorStats:
    $ref: ./modules/block.yaml#/definitions/BlockGeneratorStats

  ###
  # Memory definitions
  ###
  MemoryGenerator:
    $ref: ./modules/memory.yaml#/definitions/MemoryGenerator

  MemoryGeneratorConfig:
    $ref: ./modules/memory.yaml#/definitions/MemoryGeneratorConfig

  MemoryGeneratorResult:
    $ref: ./modules/memory.yaml#/definitions/MemoryGeneratorResult

  MemoryGeneratorStats:
    $ref: ./modules/memory.yaml#/definitions/MemoryGeneratorStats

  ###
  # CPU definitions
  ###
  CpuGenerator:
    $ref: ./modules/cpu.yaml#/definitions/CpuGenerator

  CpuGeneratorConfig:
    $ref: ./modules/cpu.yaml#/definitions/CpuGeneratorConfig

  CpuGeneratorCoreConfig:
    $ref: ./modules/cpu.yaml#/definitions/CpuGeneratorCoreConfig

  CpuGeneratorResult:
    $ref: ./modules/cpu.yaml#/definitions/CpuGeneratorResult

  CpuGeneratorStats:
    $ref: ./modules/cpu.yaml#/definitions/CpuGeneratorStats

  CpuGeneratorCoreStats:
    $ref: ./modules/cpu.yaml#/definitions/CpuGeneratorCoreStats

  CpuGeneratorTargetStats:
    $ref: ./modules/cpu.yaml#/definitions/CpuGeneratorTargetStats

  ###
  # Dynamic Results definitions
  ###
  DynamicResultsConfig:
    $ref: ./modules/dynamic.yaml#/definitions/DynamicResultsConfig

  DynamicResults:
    $ref: ./modules/dynamic.yaml#/definitions/DynamicResults

  ThresholdConfig:
    $ref: ./modules/dynamic.yaml#/definitions/ThresholdConfig

  ThresholdResult:
    $ref: ./modules/dynamic.yaml#/definitions/ThresholdResult

  TDigestConfig:
    $ref: ./modules/dynamic.yaml#/definitions/TDigestConfig

  TDigestResult:
    $ref: ./modules/dynamic.yaml#/definitions/TDigestResult

  TDigestCentroid:
    $ref: ./modules/dynamic.yaml#/definitions/TDigestCentroid
