// Code generated by go-swagger; DO NOT EDIT.

package interfaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewBulkCreateInterfacesParams creates a new BulkCreateInterfacesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewBulkCreateInterfacesParams() *BulkCreateInterfacesParams {
	return &BulkCreateInterfacesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewBulkCreateInterfacesParamsWithTimeout creates a new BulkCreateInterfacesParams object
// with the ability to set a timeout on a request.
func NewBulkCreateInterfacesParamsWithTimeout(timeout time.Duration) *BulkCreateInterfacesParams {
	return &BulkCreateInterfacesParams{
		timeout: timeout,
	}
}

// NewBulkCreateInterfacesParamsWithContext creates a new BulkCreateInterfacesParams object
// with the ability to set a context for a request.
func NewBulkCreateInterfacesParamsWithContext(ctx context.Context) *BulkCreateInterfacesParams {
	return &BulkCreateInterfacesParams{
		Context: ctx,
	}
}

// NewBulkCreateInterfacesParamsWithHTTPClient creates a new BulkCreateInterfacesParams object
// with the ability to set a custom HTTPClient for a request.
func NewBulkCreateInterfacesParamsWithHTTPClient(client *http.Client) *BulkCreateInterfacesParams {
	return &BulkCreateInterfacesParams{
		HTTPClient: client,
	}
}

/* BulkCreateInterfacesParams contains all the parameters to send to the API endpoint
   for the bulk create interfaces operation.

   Typically these are written to a http.Request.
*/
type BulkCreateInterfacesParams struct {

	/* Create.

	   Bulk creation
	*/
	Create BulkCreateInterfacesBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the bulk create interfaces params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BulkCreateInterfacesParams) WithDefaults() *BulkCreateInterfacesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the bulk create interfaces params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BulkCreateInterfacesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the bulk create interfaces params
func (o *BulkCreateInterfacesParams) WithTimeout(timeout time.Duration) *BulkCreateInterfacesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the bulk create interfaces params
func (o *BulkCreateInterfacesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the bulk create interfaces params
func (o *BulkCreateInterfacesParams) WithContext(ctx context.Context) *BulkCreateInterfacesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the bulk create interfaces params
func (o *BulkCreateInterfacesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the bulk create interfaces params
func (o *BulkCreateInterfacesParams) WithHTTPClient(client *http.Client) *BulkCreateInterfacesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the bulk create interfaces params
func (o *BulkCreateInterfacesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreate adds the create to the bulk create interfaces params
func (o *BulkCreateInterfacesParams) WithCreate(create BulkCreateInterfacesBody) *BulkCreateInterfacesParams {
	o.SetCreate(create)
	return o
}

// SetCreate adds the create to the bulk create interfaces params
func (o *BulkCreateInterfacesParams) SetCreate(create BulkCreateInterfacesBody) {
	o.Create = create
}

// WriteToRequest writes these params to a swagger request
func (o *BulkCreateInterfacesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Create); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
