// Code generated by go-swagger; DO NOT EDIT.

package memory_generator

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMemoryInfoParams creates a new MemoryInfoParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMemoryInfoParams() *MemoryInfoParams {
	return &MemoryInfoParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMemoryInfoParamsWithTimeout creates a new MemoryInfoParams object
// with the ability to set a timeout on a request.
func NewMemoryInfoParamsWithTimeout(timeout time.Duration) *MemoryInfoParams {
	return &MemoryInfoParams{
		timeout: timeout,
	}
}

// NewMemoryInfoParamsWithContext creates a new MemoryInfoParams object
// with the ability to set a context for a request.
func NewMemoryInfoParamsWithContext(ctx context.Context) *MemoryInfoParams {
	return &MemoryInfoParams{
		Context: ctx,
	}
}

// NewMemoryInfoParamsWithHTTPClient creates a new MemoryInfoParams object
// with the ability to set a custom HTTPClient for a request.
func NewMemoryInfoParamsWithHTTPClient(client *http.Client) *MemoryInfoParams {
	return &MemoryInfoParams{
		HTTPClient: client,
	}
}

/* MemoryInfoParams contains all the parameters to send to the API endpoint
   for the memory info operation.

   Typically these are written to a http.Request.
*/
type MemoryInfoParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the memory info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MemoryInfoParams) WithDefaults() *MemoryInfoParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the memory info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MemoryInfoParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the memory info params
func (o *MemoryInfoParams) WithTimeout(timeout time.Duration) *MemoryInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the memory info params
func (o *MemoryInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the memory info params
func (o *MemoryInfoParams) WithContext(ctx context.Context) *MemoryInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the memory info params
func (o *MemoryInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the memory info params
func (o *MemoryInfoParams) WithHTTPClient(client *http.Client) *MemoryInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the memory info params
func (o *MemoryInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *MemoryInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
