core:
  log:
    level: debug

modules:
  socket:
    force-unlink: true

  packetio:
    dpdk:
      options:
        - "-m256m"
        - "--no-huge"
      test-mode: true
      port-ids:
        port0: port0
        port1: port1
