// Code generated by go-swagger; DO NOT EDIT.

package packet_analyzers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStartPacketAnalyzerParams creates a new StartPacketAnalyzerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStartPacketAnalyzerParams() *StartPacketAnalyzerParams {
	return &StartPacketAnalyzerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStartPacketAnalyzerParamsWithTimeout creates a new StartPacketAnalyzerParams object
// with the ability to set a timeout on a request.
func NewStartPacketAnalyzerParamsWithTimeout(timeout time.Duration) *StartPacketAnalyzerParams {
	return &StartPacketAnalyzerParams{
		timeout: timeout,
	}
}

// NewStartPacketAnalyzerParamsWithContext creates a new StartPacketAnalyzerParams object
// with the ability to set a context for a request.
func NewStartPacketAnalyzerParamsWithContext(ctx context.Context) *StartPacketAnalyzerParams {
	return &StartPacketAnalyzerParams{
		Context: ctx,
	}
}

// NewStartPacketAnalyzerParamsWithHTTPClient creates a new StartPacketAnalyzerParams object
// with the ability to set a custom HTTPClient for a request.
func NewStartPacketAnalyzerParamsWithHTTPClient(client *http.Client) *StartPacketAnalyzerParams {
	return &StartPacketAnalyzerParams{
		HTTPClient: client,
	}
}

/* StartPacketAnalyzerParams contains all the parameters to send to the API endpoint
   for the start packet analyzer operation.

   Typically these are written to a http.Request.
*/
type StartPacketAnalyzerParams struct {

	/* ID.

	   Unique resource identifier

	   Format: string
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the start packet analyzer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StartPacketAnalyzerParams) WithDefaults() *StartPacketAnalyzerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the start packet analyzer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StartPacketAnalyzerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the start packet analyzer params
func (o *StartPacketAnalyzerParams) WithTimeout(timeout time.Duration) *StartPacketAnalyzerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the start packet analyzer params
func (o *StartPacketAnalyzerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the start packet analyzer params
func (o *StartPacketAnalyzerParams) WithContext(ctx context.Context) *StartPacketAnalyzerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the start packet analyzer params
func (o *StartPacketAnalyzerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the start packet analyzer params
func (o *StartPacketAnalyzerParams) WithHTTPClient(client *http.Client) *StartPacketAnalyzerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the start packet analyzer params
func (o *StartPacketAnalyzerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the start packet analyzer params
func (o *StartPacketAnalyzerParams) WithID(id string) *StartPacketAnalyzerParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the start packet analyzer params
func (o *StartPacketAnalyzerParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *StartPacketAnalyzerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
