/**
* Inception Core API
* REST API interface to the Inception Core
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "PortConfig_bond.h"

namespace icp {
namespace api {
namespace v1 {
namespace model {

PortConfig_bond::PortConfig_bond()
{
    m_Mode = "";
    
}

PortConfig_bond::~PortConfig_bond()
{
}

void PortConfig_bond::validate()
{
    // TODO: implement validation
}

nlohmann::json PortConfig_bond::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["mode"] = ModelBase::toJson(m_Mode);
    {
        nlohmann::json jsonArray;
        for( auto& item : m_Ports )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        val["ports"] = jsonArray;
            }
    

    return val;
}

void PortConfig_bond::fromJson(nlohmann::json& val)
{
    setMode(val.at("mode"));
    {
        m_Ports.clear();
        nlohmann::json jsonArray;
                for( auto& item : val["ports"] )
        {
            m_Ports.push_back(item);
            
        }
    }
    
}


std::string PortConfig_bond::getMode() const
{
    return m_Mode;
}
void PortConfig_bond::setMode(std::string value)
{
    m_Mode = value;
    
}
std::vector<std::string>& PortConfig_bond::getPorts()
{
    return m_Ports;
}

}
}
}
}

