/**
* Inception Core API
* REST API interface to the Inception Core
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * PortDriver.h
 *
 * Port driver information
 */

#ifndef PortDriver_H_
#define PortDriver_H_


#include "ModelBase.h"

#include "PortDriver_dpdk.h"
#include "PortDriver_bond.h"
#include "PortDriver_host.h"

namespace icp {
namespace api {
namespace v1 {
namespace model {

/// <summary>
/// Port driver information
/// </summary>
class  PortDriver
    : public ModelBase
{
public:
    PortDriver();
    virtual ~PortDriver();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// PortDriver members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<PortDriver_dpdk> getDpdk() const;
    void setDpdk(std::shared_ptr<PortDriver_dpdk> value);
    bool dpdkIsSet() const;
    void unsetDpdk();
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<PortDriver_host> getHost() const;
    void setHost(std::shared_ptr<PortDriver_host> value);
    bool hostIsSet() const;
    void unsetHost();
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<PortDriver_bond> getBond() const;
    void setBond(std::shared_ptr<PortDriver_bond> value);
    bool bondIsSet() const;
    void unsetBond();

protected:
    std::shared_ptr<PortDriver_dpdk> m_Dpdk;
    bool m_DpdkIsSet;
    std::shared_ptr<PortDriver_host> m_Host;
    bool m_HostIsSet;
    std::shared_ptr<PortDriver_bond> m_Bond;
    bool m_BondIsSet;
};

}
}
}
}

#endif /* PortDriver_H_ */
