/**
* Inception Core API
* REST API interface to the Inception Core
*
* OpenAPI spec version: 1
* Contact: support@spirent.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "Stack.h"

namespace icp {
namespace api {
namespace v1 {
namespace model {

Stack::Stack()
{
    m_Id = "";
    
}

Stack::~Stack()
{
}

void Stack::validate()
{
    // TODO: implement validation
}

nlohmann::json Stack::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["id"] = ModelBase::toJson(m_Id);
    val["stats"] = ModelBase::toJson(m_Stats);
    

    return val;
}

void Stack::fromJson(nlohmann::json& val)
{
    setId(val.at("id"));
    
}


std::string Stack::getId() const
{
    return m_Id;
}
void Stack::setId(std::string value)
{
    m_Id = value;
    
}
std::shared_ptr<StackStats> Stack::getStats() const
{
    return m_Stats;
}
void Stack::setStats(std::shared_ptr<StackStats> value)
{
    m_Stats = value;
    
}

}
}
}
}

