// Code generated by go-swagger; DO NOT EDIT.

package ports

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPortParams creates a new GetPortParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPortParams() *GetPortParams {
	return &GetPortParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPortParamsWithTimeout creates a new GetPortParams object
// with the ability to set a timeout on a request.
func NewGetPortParamsWithTimeout(timeout time.Duration) *GetPortParams {
	return &GetPortParams{
		timeout: timeout,
	}
}

// NewGetPortParamsWithContext creates a new GetPortParams object
// with the ability to set a context for a request.
func NewGetPortParamsWithContext(ctx context.Context) *GetPortParams {
	return &GetPortParams{
		Context: ctx,
	}
}

// NewGetPortParamsWithHTTPClient creates a new GetPortParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPortParamsWithHTTPClient(client *http.Client) *GetPortParams {
	return &GetPortParams{
		HTTPClient: client,
	}
}

/* GetPortParams contains all the parameters to send to the API endpoint
   for the get port operation.

   Typically these are written to a http.Request.
*/
type GetPortParams struct {

	/* ID.

	   Unique resource identifier

	   Format: string
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get port params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPortParams) WithDefaults() *GetPortParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get port params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPortParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get port params
func (o *GetPortParams) WithTimeout(timeout time.Duration) *GetPortParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get port params
func (o *GetPortParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get port params
func (o *GetPortParams) WithContext(ctx context.Context) *GetPortParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get port params
func (o *GetPortParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get port params
func (o *GetPortParams) WithHTTPClient(client *http.Client) *GetPortParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get port params
func (o *GetPortParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get port params
func (o *GetPortParams) WithID(id string) *GetPortParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get port params
func (o *GetPortParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetPortParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
