// Code generated by go-swagger; DO NOT EDIT.

package t_v_l_p

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// StopTvlpConfigurationReader is a Reader for the StopTvlpConfiguration structure.
type StopTvlpConfigurationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopTvlpConfigurationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewStopTvlpConfigurationNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewStopTvlpConfigurationNoContent creates a StopTvlpConfigurationNoContent with default headers values
func NewStopTvlpConfigurationNoContent() *StopTvlpConfigurationNoContent {
	return &StopTvlpConfigurationNoContent{}
}

/* StopTvlpConfigurationNoContent describes a response with status code 204, with default header values.

No Content
*/
type StopTvlpConfigurationNoContent struct {
}

func (o *StopTvlpConfigurationNoContent) Error() string {
	return fmt.Sprintf("[POST /tvlp/{id}/stop][%d] stopTvlpConfigurationNoContent ", 204)
}

func (o *StopTvlpConfigurationNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
