core:
  log:
    level: info

modules:
  api:
    port: 9000

  packetio:
    dpdk:
      port-ids:
        port0: port0

  socket:
    prefix: "sink"

resources:
  /interfaces/interface0:
    port_id: port0
    config:
      protocols:
        - eth:
            mac_address: "00:10:94:c0:ff:ee"
        - ipv4:
            method: static
            static:
              address: "198.19.100.2"
              prefix_length: 15
              gateway: "198.18.0.1"
