// Code generated by go-swagger; DO NOT EDIT.

package memory_generator

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewBulkDeleteMemoryGeneratorsParams creates a new BulkDeleteMemoryGeneratorsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewBulkDeleteMemoryGeneratorsParams() *BulkDeleteMemoryGeneratorsParams {
	return &BulkDeleteMemoryGeneratorsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewBulkDeleteMemoryGeneratorsParamsWithTimeout creates a new BulkDeleteMemoryGeneratorsParams object
// with the ability to set a timeout on a request.
func NewBulkDeleteMemoryGeneratorsParamsWithTimeout(timeout time.Duration) *BulkDeleteMemoryGeneratorsParams {
	return &BulkDeleteMemoryGeneratorsParams{
		timeout: timeout,
	}
}

// NewBulkDeleteMemoryGeneratorsParamsWithContext creates a new BulkDeleteMemoryGeneratorsParams object
// with the ability to set a context for a request.
func NewBulkDeleteMemoryGeneratorsParamsWithContext(ctx context.Context) *BulkDeleteMemoryGeneratorsParams {
	return &BulkDeleteMemoryGeneratorsParams{
		Context: ctx,
	}
}

// NewBulkDeleteMemoryGeneratorsParamsWithHTTPClient creates a new BulkDeleteMemoryGeneratorsParams object
// with the ability to set a custom HTTPClient for a request.
func NewBulkDeleteMemoryGeneratorsParamsWithHTTPClient(client *http.Client) *BulkDeleteMemoryGeneratorsParams {
	return &BulkDeleteMemoryGeneratorsParams{
		HTTPClient: client,
	}
}

/* BulkDeleteMemoryGeneratorsParams contains all the parameters to send to the API endpoint
   for the bulk delete memory generators operation.

   Typically these are written to a http.Request.
*/
type BulkDeleteMemoryGeneratorsParams struct {

	/* Delete.

	   Bulk delete
	*/
	Delete BulkDeleteMemoryGeneratorsBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the bulk delete memory generators params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BulkDeleteMemoryGeneratorsParams) WithDefaults() *BulkDeleteMemoryGeneratorsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the bulk delete memory generators params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BulkDeleteMemoryGeneratorsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the bulk delete memory generators params
func (o *BulkDeleteMemoryGeneratorsParams) WithTimeout(timeout time.Duration) *BulkDeleteMemoryGeneratorsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the bulk delete memory generators params
func (o *BulkDeleteMemoryGeneratorsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the bulk delete memory generators params
func (o *BulkDeleteMemoryGeneratorsParams) WithContext(ctx context.Context) *BulkDeleteMemoryGeneratorsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the bulk delete memory generators params
func (o *BulkDeleteMemoryGeneratorsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the bulk delete memory generators params
func (o *BulkDeleteMemoryGeneratorsParams) WithHTTPClient(client *http.Client) *BulkDeleteMemoryGeneratorsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the bulk delete memory generators params
func (o *BulkDeleteMemoryGeneratorsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDelete adds the delete to the bulk delete memory generators params
func (o *BulkDeleteMemoryGeneratorsParams) WithDelete(delete BulkDeleteMemoryGeneratorsBody) *BulkDeleteMemoryGeneratorsParams {
	o.SetDelete(delete)
	return o
}

// SetDelete adds the delete to the bulk delete memory generators params
func (o *BulkDeleteMemoryGeneratorsParams) SetDelete(delete BulkDeleteMemoryGeneratorsBody) {
	o.Delete = delete
}

// WriteToRequest writes these params to a swagger request
func (o *BulkDeleteMemoryGeneratorsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Delete); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
