// Code generated by go-swagger; DO NOT EDIT.

package memory_generator

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/spirent/openperf/api/client/golang/models"
)

// BulkCreateMemoryGeneratorsReader is a Reader for the BulkCreateMemoryGenerators structure.
type BulkCreateMemoryGeneratorsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BulkCreateMemoryGeneratorsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewBulkCreateMemoryGeneratorsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewBulkCreateMemoryGeneratorsOK creates a BulkCreateMemoryGeneratorsOK with default headers values
func NewBulkCreateMemoryGeneratorsOK() *BulkCreateMemoryGeneratorsOK {
	return &BulkCreateMemoryGeneratorsOK{}
}

/* BulkCreateMemoryGeneratorsOK describes a response with status code 200, with default header values.

Success
*/
type BulkCreateMemoryGeneratorsOK struct {
	Payload []*models.MemoryGenerator
}

func (o *BulkCreateMemoryGeneratorsOK) Error() string {
	return fmt.Sprintf("[POST /memory-generators/x/bulk-create][%d] bulkCreateMemoryGeneratorsOK  %+v", 200, o.Payload)
}
func (o *BulkCreateMemoryGeneratorsOK) GetPayload() []*models.MemoryGenerator {
	return o.Payload
}

func (o *BulkCreateMemoryGeneratorsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*BulkCreateMemoryGeneratorsBody BulkCreateMemoryGeneratorsRequest
//
// Parameters for the bulk create operation
swagger:model BulkCreateMemoryGeneratorsBody
*/
type BulkCreateMemoryGeneratorsBody struct {

	// List of memory generators
	// Required: true
	// Min Items: 1
	Items []*models.MemoryGenerator `json:"items"`
}

// Validate validates this bulk create memory generators body
func (o *BulkCreateMemoryGeneratorsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateItems(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *BulkCreateMemoryGeneratorsBody) validateItems(formats strfmt.Registry) error {

	if err := validate.Required("create"+"."+"items", "body", o.Items); err != nil {
		return err
	}

	iItemsSize := int64(len(o.Items))

	if err := validate.MinItems("create"+"."+"items", "body", iItemsSize, 1); err != nil {
		return err
	}

	for i := 0; i < len(o.Items); i++ {
		if swag.IsZero(o.Items[i]) { // not required
			continue
		}

		if o.Items[i] != nil {
			if err := o.Items[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("create" + "." + "items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this bulk create memory generators body based on the context it is used
func (o *BulkCreateMemoryGeneratorsBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateItems(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *BulkCreateMemoryGeneratorsBody) contextValidateItems(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Items); i++ {

		if o.Items[i] != nil {
			if err := o.Items[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("create" + "." + "items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *BulkCreateMemoryGeneratorsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *BulkCreateMemoryGeneratorsBody) UnmarshalBinary(b []byte) error {
	var res BulkCreateMemoryGeneratorsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
