// Code generated by go-swagger; DO NOT EDIT.

package memory_generator

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteMemoryGeneratorParams creates a new DeleteMemoryGeneratorParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteMemoryGeneratorParams() *DeleteMemoryGeneratorParams {
	return &DeleteMemoryGeneratorParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteMemoryGeneratorParamsWithTimeout creates a new DeleteMemoryGeneratorParams object
// with the ability to set a timeout on a request.
func NewDeleteMemoryGeneratorParamsWithTimeout(timeout time.Duration) *DeleteMemoryGeneratorParams {
	return &DeleteMemoryGeneratorParams{
		timeout: timeout,
	}
}

// NewDeleteMemoryGeneratorParamsWithContext creates a new DeleteMemoryGeneratorParams object
// with the ability to set a context for a request.
func NewDeleteMemoryGeneratorParamsWithContext(ctx context.Context) *DeleteMemoryGeneratorParams {
	return &DeleteMemoryGeneratorParams{
		Context: ctx,
	}
}

// NewDeleteMemoryGeneratorParamsWithHTTPClient creates a new DeleteMemoryGeneratorParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteMemoryGeneratorParamsWithHTTPClient(client *http.Client) *DeleteMemoryGeneratorParams {
	return &DeleteMemoryGeneratorParams{
		HTTPClient: client,
	}
}

/* DeleteMemoryGeneratorParams contains all the parameters to send to the API endpoint
   for the delete memory generator operation.

   Typically these are written to a http.Request.
*/
type DeleteMemoryGeneratorParams struct {

	/* ID.

	   Unique resource identifier

	   Format: string
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete memory generator params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteMemoryGeneratorParams) WithDefaults() *DeleteMemoryGeneratorParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete memory generator params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteMemoryGeneratorParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete memory generator params
func (o *DeleteMemoryGeneratorParams) WithTimeout(timeout time.Duration) *DeleteMemoryGeneratorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete memory generator params
func (o *DeleteMemoryGeneratorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete memory generator params
func (o *DeleteMemoryGeneratorParams) WithContext(ctx context.Context) *DeleteMemoryGeneratorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete memory generator params
func (o *DeleteMemoryGeneratorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete memory generator params
func (o *DeleteMemoryGeneratorParams) WithHTTPClient(client *http.Client) *DeleteMemoryGeneratorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete memory generator params
func (o *DeleteMemoryGeneratorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete memory generator params
func (o *DeleteMemoryGeneratorParams) WithID(id string) *DeleteMemoryGeneratorParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete memory generator params
func (o *DeleteMemoryGeneratorParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteMemoryGeneratorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
