// Code generated by go-swagger; DO NOT EDIT.

package interfaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteInterfaceParams creates a new DeleteInterfaceParams object
// with the default values initialized.
func NewDeleteInterfaceParams() *DeleteInterfaceParams {
	var ()
	return &DeleteInterfaceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteInterfaceParamsWithTimeout creates a new DeleteInterfaceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteInterfaceParamsWithTimeout(timeout time.Duration) *DeleteInterfaceParams {
	var ()
	return &DeleteInterfaceParams{

		timeout: timeout,
	}
}

// NewDeleteInterfaceParamsWithContext creates a new DeleteInterfaceParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteInterfaceParamsWithContext(ctx context.Context) *DeleteInterfaceParams {
	var ()
	return &DeleteInterfaceParams{

		Context: ctx,
	}
}

// NewDeleteInterfaceParamsWithHTTPClient creates a new DeleteInterfaceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteInterfaceParamsWithHTTPClient(client *http.Client) *DeleteInterfaceParams {
	var ()
	return &DeleteInterfaceParams{
		HTTPClient: client,
	}
}

/*DeleteInterfaceParams contains all the parameters to send to the API endpoint
for the delete interface operation typically these are written to a http.Request
*/
type DeleteInterfaceParams struct {

	/*ID
	  Unique resource identifier

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete interface params
func (o *DeleteInterfaceParams) WithTimeout(timeout time.Duration) *DeleteInterfaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete interface params
func (o *DeleteInterfaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete interface params
func (o *DeleteInterfaceParams) WithContext(ctx context.Context) *DeleteInterfaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete interface params
func (o *DeleteInterfaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete interface params
func (o *DeleteInterfaceParams) WithHTTPClient(client *http.Client) *DeleteInterfaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete interface params
func (o *DeleteInterfaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete interface params
func (o *DeleteInterfaceParams) WithID(id string) *DeleteInterfaceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete interface params
func (o *DeleteInterfaceParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteInterfaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
