// Code generated by go-swagger; DO NOT EDIT.

package interfaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/Spirent/openperf/targets/spiperf/openperf/v1/models"
)

// ListInterfacesReader is a Reader for the ListInterfaces structure.
type ListInterfacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListInterfacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListInterfacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListInterfacesOK creates a ListInterfacesOK with default headers values
func NewListInterfacesOK() *ListInterfacesOK {
	return &ListInterfacesOK{}
}

/*ListInterfacesOK handles this case with default header values.

Success
*/
type ListInterfacesOK struct {
	Payload []*models.Interface
}

func (o *ListInterfacesOK) Error() string {
	return fmt.Sprintf("[GET /interfaces][%d] listInterfacesOK  %+v", 200, o.Payload)
}

func (o *ListInterfacesOK) GetPayload() []*models.Interface {
	return o.Payload
}

func (o *ListInterfacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
