core:
  log:
    level: debug

modules:
  plugins:
    load:
      - "libopenperf_tvlp.so"
    path: "/opt/openperf/plugins"
  api:
    port: 9000

  socket:
    force-unlink: true

  packetio:
    dpdk:
      options:
        - "-m256m"
        - "--no-huge"
      test-mode: true
      port-ids:
        port0: port0
        port1: port1
