// Code generated by go-swagger; DO NOT EDIT.

package sockets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSocketStatsParams creates a new GetSocketStatsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSocketStatsParams() *GetSocketStatsParams {
	return &GetSocketStatsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSocketStatsParamsWithTimeout creates a new GetSocketStatsParams object
// with the ability to set a timeout on a request.
func NewGetSocketStatsParamsWithTimeout(timeout time.Duration) *GetSocketStatsParams {
	return &GetSocketStatsParams{
		timeout: timeout,
	}
}

// NewGetSocketStatsParamsWithContext creates a new GetSocketStatsParams object
// with the ability to set a context for a request.
func NewGetSocketStatsParamsWithContext(ctx context.Context) *GetSocketStatsParams {
	return &GetSocketStatsParams{
		Context: ctx,
	}
}

// NewGetSocketStatsParamsWithHTTPClient creates a new GetSocketStatsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSocketStatsParamsWithHTTPClient(client *http.Client) *GetSocketStatsParams {
	return &GetSocketStatsParams{
		HTTPClient: client,
	}
}

/* GetSocketStatsParams contains all the parameters to send to the API endpoint
   for the get socket stats operation.

   Typically these are written to a http.Request.
*/
type GetSocketStatsParams struct {

	/* ID.

	   Unique resource identifier

	   Format: string
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get socket stats params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSocketStatsParams) WithDefaults() *GetSocketStatsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get socket stats params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSocketStatsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get socket stats params
func (o *GetSocketStatsParams) WithTimeout(timeout time.Duration) *GetSocketStatsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get socket stats params
func (o *GetSocketStatsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get socket stats params
func (o *GetSocketStatsParams) WithContext(ctx context.Context) *GetSocketStatsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get socket stats params
func (o *GetSocketStatsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get socket stats params
func (o *GetSocketStatsParams) WithHTTPClient(client *http.Client) *GetSocketStatsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get socket stats params
func (o *GetSocketStatsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get socket stats params
func (o *GetSocketStatsParams) WithID(id string) *GetSocketStatsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get socket stats params
func (o *GetSocketStatsParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetSocketStatsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
